<?php
/**
 * Magento
 *
 * @copyright  Copyright (c) 2009 Ekkitab Educational Services Pvt Ltd (http://www.ekkitab.com)
 *
 * All  Categories List template
 *
 */
?>
<div class="allCategoriesArea">
<div class="pageHeader">Book categories on ekkitab</div>
<br class="clear" />
<?php
	$categories = Mage::helper('catalog/category')->getStoreCategories();
	$_count = is_array($categories)?count($categories):$categories->count(); 
	$_columns =3;
	$_totalRows= intval($_count/ $_columns) ;
	$_totalRows= ($_count % $_columns) > 0 ? $_totalRows +1 : $_totalRows  ;
	$_counter=0;
	$_firstColumn=1;
	if($_count): 
		foreach ($categories as $category): 
?>			
<?php if($_counter==$_totalRows):
		$_counter =0; ?>
		</ul></div>
<?php endif; ?>

<?php if($_counter==0):
		if($_firstColumn):
			$_firstColumn =0; ?>
			<div class="allCategoriesListsFirst">
<?php	else: ?>
			<div class="allCategoriesLists">
<?php	endif; ?>
			<ul>
<?php endif; ?>

			<?php if($category->getIsActive()):
				$url = $this->helper('ekkitab_catalog')->getEncodedString($category->getName());
				$url = $this->helper('ekkitab_catalog')->getSearchResultByIndexUrl(null,array('category' => $url));
			?>
			 <li>
				<a href="<?php echo $url ?>"<?php if ($this->isCategoryActive($category)): ?> class="active"<?php endif ?>><?php echo $this->htmlEscape($category->getName()) ?></a> </li>
			<?php endif; ?>
<?php	$_counter= $_counter +1;
		endforeach; ?>
	</ul></div>
<?php endif; ?>
<div class="clear"></div>
</div><!-- allCategoriesArea -->

