<?php
/**
 * 
 * Frontend  Catalog Category search results template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Dec 7, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php
	$pages=$this->getPages();
?>
<div class="fullCatalogMainArea">
<?php 
  if (!is_null($pages) && count($pages) > 0) {
 ?>
	
	<div class="inLeft">
		<?php echo $this->getMessagesBlock()->getGroupedHtml()  ?>
		<?php if ($messages = $this->getNoteMessages()):?>
			<div class="note-msg">
				<?php foreach ($messages as $message):?>
				<?php echo $message?><br />
				<?php endforeach;?>
			</div>
		<?php endif; ?>
		<div class="searchResTop">
			<div class="leftArea">
				<?php foreach ($pages as $_page): ?>
						<a class="slots" href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a>&nbsp;
				<?php endforeach; ?>
			</div><!-- leftArea -->
			<div class="clear"></div>
		</div><!-- searchResTop -->
	</div><!-- inLeft-->
	<div class="clear"></div>
<?php
		} 	
		else { // else of if (!java_is_null(bookList))
?>			<div class="inLeft">
				<div class="boldFont orangeTxt12"></div> 
				<div class="clear"><br/></div>
			</div>
		</div><div class="clear"></div>
<?php } // ending of else of if (!java_is_null(bookList))
?>
</div>
