<?php
/**
 * 
 * Frontend Popular Categories Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$_categories= $this->getPopularCategories();
		$_count = is_array($_categories)?count($_categories):$_categories->count(); 
		$repArr1= array(" & ",
						"&");

?>
<div class="linkHdr">Popular Categories</div><!-- linkHdr -->
<ul>
<?php if($_count): ?>
	<?php foreach ($_categories as $_category): ?>
		<?php if($_category->getIsActive()): 
				$randNo = 10 * $_category->getPopularity();
				$url =  $_category->getCategory();
				$url = str_replace($repArr1, "_", $url);
				//	$url = str_replace($repArr2, "-", $url);
				$url = preg_replace('#[^A-Za-z0-9\_]+#', '-', $url);
				$url ="ekkitab_catalog/search/index/category/".$url;

			?>
			<li>
				<!--a href="<?php echo $_category->getUrlPath() ?>"><?php echo $this->htmlEscape($_category->getCategory()) ?></a></li-->
				<a href="<?php echo $this->getUrl($url) ?>"><?php echo $this->htmlEscape($_category->getCategory()) ?></a></li>
		<?php endif; ?>
	<?php endforeach ?>
<?php endif; ?>
</ul>
<div class="seeAll"><a href="ekkitab_catalog/category/viewAll" >See all &raquo;</a></div><!-- seeAll -->
