<?php
/**
 * 
 * Frontend Popular Categories Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$_categories= $this->getPopularCategories();
		$_count = is_array($_categories)?count($_categories):$_categories->count(); 
?>
<div class="popular-categories right" >
	<div class="head" >
		<h4> Popular Subjects </h4>
	</div>	
	<div class="content">
		<ul>
		<?php if($_count): ?>
			<?php foreach ($_categories as $_category): ?>
				<?php if($_category->getIsActive()): 
						$randNo = 10 * $_category->getPopularity();
					?>
					<li>
						<a style="font-size:<?php echo $randNo?>%;" href="<?php echo $_category->getUrlPath() ?>"><?php echo $this->htmlEscape($_category->getCategory()) ?></a>&nbsp;
					</li>
				<?php endif; ?>
			<?php endforeach ?>
		<?php endif; ?>
		</ul>
		<span class="right"><a href="ekkitab_catalog/category/viewAll">View All</a> </span>
	</div>	
</div>