<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$products= $this->getBestsellers();
		$_count = is_array($products)?count($products):$products->count(); 
?>
<?php if($_count): ?>
	<div class="hmScrollRow">
		<div class="mainLeftHdr">Best Sellers</div>
		<div class="hmInScrollRow">
		<?php foreach ($products as $product): ?>
			<div class="vColumns">
				<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(false)->resize(null, 100); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" />
				</a> 
				<div class="titleEtc">
					<div class="bkTitle"><a href="<?php echo $product->getProductUrl() ?>"  title="<?php echo $product->getTitle() ?>"><?php echo $this->htmlEscape($product->getName())?></a></div><!-- bkTitle -->
					<div class="authorEtc">Steven D. Levitt</div>
					<div class="authorEtc">Our Price: Rs. 340</div>
					<div class="youSave">Save 19% off</div>
				</div><!-- titleEtc -->
			</div>
		<?php endforeach ?>
		<div class="clear"></div>
		</div><!-- hmInScrollRow -->
	</div><!-- hmScrollRow -->
<?php else: ?>
	<div class="hmMainRows">
		<div class="mainLeftHdr">Best Sellers</div>This section will be updated soon.
	</div><!-- hmMainRows -->
<?php endif; ?>

