<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$products= $this->getBestBoxedSets()->getItems();
		$productIds= $this->getBestBoxedSetsProductIds();
		$_count = is_array($products)?count($products):$products->count(); 
		$_columnSize=4;
?>
<?php if($_count):
	$_totalRows= intval($_count/ $_columnSize) ;
	$_totalRows= ($_count % $_columnSize) > 0 ? $_totalRows +1 : $_totalRows  ;
	//Mage::log("count size is :$_count ; rowsize is ; $_totalRows");
?>
<script language="javascript">
	var totalDivCount=<?php echo $_totalRows ?>;
</script>
<div class="hmScrollRow">
	<div class="mainLeftHdr">Best Boxed Sets</div>
		<?php for($i=0 ; $i < $_totalRows ; $i++){ 
				$start = $i * $_columnSize ;
				$end= $start + $_columnSize ;
				$end = $end > $_count ? $_count : $end;

		?>
		<div class="hmInScrollRow<?php echo ($i==0)?  "" : " hideReviewForm" ?>" id="bestboxedsets_scroll_<?php echo $i+1 ?>" >
			<div class="hmLeftScroll"><a href="javascript:showRequest('bestboxedsets',<?php echo $i+1 ?>,<?php echo $i ?>)"><img src="<?php echo $this->getSkinUrl('/images/hm_left_scroll.jpg') ?>" width="17" height="41" border="0" /></a></div>
			<?php for($j=$start ; $j < $end ; $j++){ 
				$productId = $productIds[$j];
				$product = $products[$productId];
				$savingsPerct= ($product->getPrice() >0 )?	(($product->getPrice() - $product->getFinalPrice())/ $product->getPrice() ) * 100 : 0; 
				$author = $product->getBoAuthor();
				$title= $this->htmlEscape($product->getName());
				if(isset($author) && strlen(trim($author)) > 0)
				{
					$bookName=$author."__";
				}else{
					$bookName="";
				}
				$bookName=$bookName.$title."__".$product->getId();
				$bookName = preg_replace('#[^A-Za-z0-9\_]+#', '-', $bookName);//($repArr2, "-", $urlKey);
				$bookName="ekkitab_catalog/product/view/book/".$bookName.".html";
			
			?>
			<div class="vColumns">
				<a href="<?php echo $this->getUrl($bookName)?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(false)->resize(null, 100); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" /></a>
				<div class="titleEtc">
					<div class="bkTitle"><a href="<?php echo $this->getUrl($bookName)?>"  title="<?php echo $product->getTitle() ?>"><?php echo $title ?></a></div><!-- bkTitle -->
					<div class="lineHeight14em"><?php echo $this->htmlEscape($product->getBoAuthor())?></div>
					<div class="lineHeight14em">Our Price: <?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,false) ?></div>
					<?php if($savingsPerct > 0):?><div class="youSave">Save <?php echo number_format($savingsPerct,2,'.','') ?>%</div><?php endif; ?>
				</div><!-- titleEtc -->
			</div>
			<?php } ?>
			<div class="hmRightScroll"><a href="javascript:showRequest('bestboxedsets',<?php echo $i+1 ?>,<?php echo $i+2 ?>)"><img src="<?php echo $this->getSkinUrl('/images/hm_right_scroll.jpg') ?>" width="17" height="41" border="0" /></a></div>
		</div><!-- hmInScrollRow -->
		<div class="clear"></div>
		<?php } ?>
	</div><!-- hmScrollRow -->
<?php else: ?>
	<div class="hmMainRows">
		<div class="mainLeftHdr">Best Boxed Sets</div>This section will be updated soon.
	</div><!-- hmMainRows -->
<?php endif; ?>

