<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$products= $this->getBestBoxedSets();
		$_count = is_array($products)?count($products):$products->count(); 
?>
<div class="promo-box" >
    <h3>Best Boxed Sets</h3>
	<table border="0" cellspacing="0">
		<tbody>
		<?php if($_count): ?>
			<tr class="odd">
				<?php foreach ($products as $product): ?>
				<td><p class="product-image">
					 <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(false)->resize(null, 170); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" />
					</a></p><p><a href="<?php echo $product->getProductUrl() ?>"  title="<?php echo $product->getTitle() ?>"><?php echo $this->htmlEscape($product->getName())?></a></p>
				</td>
				<?php endforeach ?>
			</tr>
			<?php else: ?>
				<tr class="odd"><td style="width:100%">This section will be updated soon</td></tr>
			<?php endif; ?>
         </tbody>
	</table>
</div>