<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$products= $this->getNewreleases();
		$_count = is_array($products)?count($products):$products->count(); 
		$repArr1= array(" & ",
						"&");
?>
<?php if($_count): ?>
	<div class="hmScrollRow">
		<div class="mainLeftHdr">New Releases</div>
		<div class="hmInScrollRow">
		<?php foreach ($products as $product): 
			$savingsPerct= ($product->getPrice() >0 )?	(($product->getPrice() - $product->getFinalPrice())/ $product->getPrice() ) * 100 : 10; 
			$author = $product->getBoAuthor();
			$title= $this->htmlEscape($product->getName());
			if(isset($author) && strlen(trim($author)) > 0)
			{
				$bookName=$author."__";
			}else{
				$bookName="";
			}
			$bookName=$bookName.$title."__".$product->getId();
			$bookName = preg_replace('#[^A-Za-z0-9\_]+#', '-', $bookName);//($repArr2, "-", $urlKey);
			$bookName="ekkitab_catalog/product/view/book/".$bookName.".html";
		
		?>
			<div class="vColumns">
				<a href="<?php echo $this->getUrl($bookName)?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(false)->resize(null, 100); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" />
				</a> 
				<div class="titleEtc">
					<div class="bkTitle"><a href="<?php echo $this->getUrl($bookName)?>"  title="<?php echo $product->getTitle() ?>"><?php echo $title ?></a></div><!-- bkTitle -->
					<div class="lineHeight14em"><?php echo $this->htmlEscape($product->getBoAuthor())?></div>
					<div class="lineHeight14em">Our Price: <?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,false) ?></div>
					<div class="youSave">Save <?php echo number_format($savingsPerct,2,'.','') ?>%</div>
				</div><!-- titleEtc -->
			</div>
		<?php endforeach ?>
		<div class="clear"></div>
		</div><!-- hmInScrollRow -->
	</div><!-- hmScrollRow -->
<?php else: ?>
	<div class="hmMainRows">
		<div class="mainLeftHdr">New Releases</div>This section will be updated soon.
	</div><!-- hmMainRows -->
<?php endif; ?>
