<?php
/**
 * 
 * Frontend Global Section Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php $section= $this->getGlobalsection();?>
<?php if($section && $section->getId()):
		$randomize = false;
		$pageNo = $this->getCurrentPageNumber();
		$_columnSize=5;
		$_deziredRows= 3;
		$limit = $_columnSize * $_deziredRows;
		//$limit = $this->getPageSize();
		$products= $section->getSectionProducts($randomize,$pageNo,$limit);
		//$productIds= $section->getSectionProductIds();
		$_count = (!is_null($products) && is_array($products))?count($products):(!is_null($products))? $products->count() :0; 
		$_columnSize=5;
		$width=(int) 100/$_columnSize;
		$counter=0;
		$firstRow=0;
		$rowNo=1;
		if($_count > 0){
			$_totalRows= intval($_count/ $_columnSize) ;
			$_totalRows= ($_count % $_columnSize) > 0 ? $_totalRows +1 : $_totalRows  ;
		}else{
			$_totalRows= 0;
		}
?>
	<!--div class="spSectionImage">
	<img src="<?php echo $this->getSkinUrl("images/ind_classic_image.jpg") ?>"/></div-->
	<div class="hmScrollRow" >
	<div class="mainHdr"><?php echo $section->getDisplayName() ?></div>
	<div class="spHdrsNoTopMargin">Classics do not die. They are forever. Stories of love and war, of life and death, of epic moments in history that are told and retold over the centuries never to die but to always teach, inform, rejuvenate, enthrall and mesmerise...Here is a collection that you will enjoy, stories that you may have read but would like to read again and again and again..	</div><!-- spHdrs -->
<?php if(!is_null($products) && $_count > 0){ ?>
<?php 		foreach($products as $product){  ?>
<?php		if($counter%$_columnSize==0){  ?>
<?php			if($firstRow!=0){	?>
					</div>
					<div class="clear hmInScrollRowSep" id="sep_<?php echo $rowNo?>"></div>
<?php				$rowNo+=1;  
				}					?>
				<div class="hmInScrollRow" id="gs_row_<?php echo $rowNo?>">
<?php		}
			$counter+=1;
			$savingsPerct= round(($product->getPrice() >0 )?	(($product->getPrice() - $product->getFinalPrice())/ $product->getPrice() ) * 100 : 0); 
			$authorArr = $product->getAuthor();
			$author = (($author = $authorArr['a'])!='')? "by <a href=\"".$this->getUrl('ekkitab_catalog/search/index/author/'.$author)."\">".$author."</a>":"" ;
			$binding = trim($product->getBinding());
			$lang = trim($product->getLanguage());
			$langNbind=strlen($lang) > 0 ? ("[".ucfirst($lang).(strlen($binding) > 0 ?" - ".ucfirst($binding)."]":"]")):(strlen($binding) > 0 ?"[".ucfirst($binding)."]":"");

			$titleWords = explode(" ",$product->getTitle());
			$title="";//$product->getTitle();
			$wordCount=3;
			$wrdCounter=0;
			if($titleWords && count($titleWords) >0 ){
				foreach($titleWords as $words){
					if($wrdCounter < $wordCount){
						$title.=$words." ";
						$wrdCounter++;
					}else{
						break;
					}
				}
			}
			$title= trim($title);
			if(count($titleWords)>$wordCount){
				$title.="...";
			}
			$fullTitle= $this->htmlEscape($product->getTitle());

			if(isset($authorArr['a']) && strlen(trim($authorArr['a'])) > 0)
			{
				$auth=trim($authorArr['a'])."__";
			}else{
				$auth="";
			}
			$bookName=$this->helper('ekkitab_catalog')->getSearchResultProductUrl($auth,$title,$product->getIsbn());
			$image = $product->getImage();
	?>
				<div class="vColumns" style="width:<?php echo $width ?>%;"><div class="discImageBox"><div class="image">
					<a href="<?php echo $this->getUrl($bookName)?>" title="<?php echo $fullTitle ?>"><img src="<?php echo $this->helper('ekkitab_catalog')->resize($image,'small_image',false,null, 109); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" /></a></div><div class="fsu<?php echo $savingsPerct?>"></div>
					</div>
				<div class="titleEtc">
						<div class="bkTitleHome"><a href="<?php echo $this->getUrl($bookName)?>"  title="<?php echo $fullTitle ?>"><?php echo $title ?></a></div><!-- bkTitle -->
						<div class="authorHome"><?php echo $author?></div>
						<!--div class="lineHeight14emIt"><?php echo $langNbind ?></div-->
						<div class="youSave"><?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,false) ?></div>
						<?php if($savingsPerct > 0):?>
						<div class="lineHeight14em"><span class="greyFont">MRP: <?php echo Mage::helper('core')->currency($product->getListPrice(),true,false) ?></span></div>
						<div class="youSave">Save <?php echo $savingsPerct ?>%</div>
						<?php endif; ?>
					</div><!-- titleEtc -->
				</div>
<?php		if($counter%$_columnSize==0){ 
				
				$firstRow =1;
			}
		}					?>
		</div><!-- hmInScrollRow -->
		<div class="clear hmInScrollRowSep"></div>
		<div class="clear"></div>
	</div><!-- hmScrollRow -->
	<div class="paginationAreaOut">
		<div class="paginationArea">
		<?php if($this->getLastPageNumber()>0): ?>
		<ul>
			<?php if (!$this->isFirstPage()): ?>
				<li><a href="<?php echo $this->getPreviousPageUrl() ?>" id="prev"><?php echo $this->__('Prev') ?></a></li>
			<?php else: ?>
				<li class="nolink"><?php echo $this->__('Prev') ?></li>
			<?php endif; ?>
			
			<?php foreach ($this->getPages() as $_page): ?>
				<?php if ($this->isPageCurrent($_page)): ?>
					<li><span><?php echo $_page ?></span></li>
				<?php else: ?>
					<li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
				<?php endif ?>
			<?php endforeach; ?>

			<?php if (!$this->isLastPage()): ?>
				<li><a href="<?php echo $this->getNextPageUrl() ?>"><?php echo $this->__('Next') ?></a></li>
			<?php else: ?>
				<li><b id="sep"><?php echo $this->__('Next') ?></b></li>
			<?php endif; ?>
		</ul>
		<?php endif; ?>
		</div><!-- paginationArea-->
	</div><!-- paginationAreaOut-->
	<div class="clear"></div>
<?php } else { //end of if(products not null )... ?>
	<div class="hmScrollRow">
			This section will be updated soon...
	</div><!-- hmScrollRow -->
</div>
<?php } //end of else ..?>
	<div class="spBotImage">
	<img src="<?php echo $this->getSkinUrl("images/ind_classic_bot_image.jpg")?>" /></div>
	<!-- spBotImage -->
<?php else: ?>
<div class="hmMainRows">
	<div class="mainLeftHdr">Special Apologies...</div>
	<div class="notFoundArea">
		<p> The content you have requested for is not available.
		<ul>

		<li>If you typed the URL directly, please make sure that the spelling is correct.</li>
		<li>If you clicked on a link to get here, the link might be outdated</li></ul>
		</p>
		<p><div class="boldFont">What can you do?</div>
		Please contact Customer Care at <a href="mailto:ccare@ekkitab.com">ccare@ekkitab.com</a> and let us know of this problem. We appreciate your help in ensuring that the service is available and runs error free.
		<ul>
		<li>Go <a href="#">back to the previous page</a></li>
		<li>Use the <a href="#">Search Facility</a> at the top of the page to search the ekkitab web site</li>
		<li>Click on any of the links below to get you back on track
		<ul><li><a href="#">ekkitab Home Page</a></li>
		<li><a href="#">My Account</a> (You will have to Sign in or Register, if it's your first time)</li>
		</ul>
		</li></ul>
		</p>
	</div><!-- notFoundArea -->
</div><!-- hmMainRows -->
<?php endif; ?>
