<?php
/**
 * 
 * Frontend Global Section Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php $section= $this->getHomePageSection();
	  $_columnSize=4;
	  $_deziredRows= 1;
?>
<?php if(!is_null($section) && $section->getId() >0 ):
		$randomize = true;
		$limit = $_columnSize * $_deziredRows;
		$pageNo = 1;
		$products= $section->getSectionProducts($randomize,$pageNo,$limit);
		//$productIds= $section->getSectionProductIds();
		$_count = (!is_null($products) && is_array($products))?count($products):(!is_null($products))? $products->count() :0; 
		$width=(int) 100/$_columnSize;
		$counter=0;
		$firstTime=0;
		if($_count > 0){
			$_totalRows= intval($_count/ $_columnSize) ;
			$_totalRows= ($_count % $_columnSize) > 0 ? $_totalRows +1 : $_totalRows  ;
		}else{
			$_totalRows= 0;
		}
		$_totalRows= 1;
?>
<div class="hmSummerRow">
	<div class="hmSummerTextImage">
		Summer is the time when you <br>sweat in the heat with your throat parched, <br> and you yearn for that cool something to slake your<br> thirst.  Summer is the time when you discover how cool your home is when you come in from the sun. So here is our summer collection ....
		<div class="hmScrollRow">
<?php	if(!is_null($products) && $_count > 0){
			foreach($products as $product){  
				if($counter%$_columnSize==0){  
				    if($firstTime!=0){  ?>
						</div>
						<div class="clear hmInScrollRowSep"></div>
<?php				}					?>
					<div class="hmInScrollRow" >
<?php			}
				$counter+=1;
				$savingsPerct= ($product->getPrice() >0 )?	(($product->getPrice() - $product->getFinalPrice())/ $product->getPrice() ) * 100 : 0; 
				$authorArr = $product->getAuthor();
				$author = ($authorArr['a']!='')? "by ".$authorArr['a']:"" ;
				$binding = trim($product->getBinding());
				$lang = trim($product->getLanguage());
				$langNbind=strlen($lang) > 0 ? ("[".ucfirst($lang).(strlen($binding) > 0 ?" - ".ucfirst($binding)."]":"]")):(strlen($binding) > 0 ?"[".ucfirst($binding)."]":"");

				$title= $this->htmlEscape($product->getName());
				if(isset($author) && strlen(trim($author)) > 0)
				{
					$bookName=$author."__";
				}else{
					$bookName="";
				}
				$bookName=$bookName.$title."__".$product->getId();
				$bookName = preg_replace('#[^A-Za-z0-9\_]+#', '-', $bookName);//($repArr2, "-", $urlKey);
				$bookName="ekkitab_catalog/product/view/book/".$bookName.".html";

				$image = $product->getImage();

	?>
				<div class="vColumns" style="width:<?php echo $width ?>%;" >
					<div class="image"><a href="<?php echo $this->getUrl($bookName)?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>"><img src="<?php echo $this->helper('ekkitab_catalog')->resize($image,'small_image',false,null, 109); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" /></a>
					</div>
				<div class="titleEtc">
						<div class="bkTitle"><a href="<?php echo $this->getUrl($bookName)?>"  title="<?php echo $product->getTitle() ?>"><?php echo $title ?></a></div><!-- bkTitle -->
						<div class="lineHeight14em"><?php echo $author?></div>
						<div class="lineHeight14emIt"><?php echo $langNbind ?></div>
						<!--div class="youSave"><?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,false) ?></div>
						<div class="lineHeight14em"><span class="striked"><?php echo Mage::helper('core')->currency($product->getListPrice(),true,false) ?></span></div>
						<?php if($savingsPerct > 0):?><div class="youSave">Save <?php echo number_format($savingsPerct,2,'.','') ?>%</div><?php endif; ?> -->
					</div><!-- titleEtc -->
				</div>
<?php			$firstTime =1;
			}	//end of foreach...	?>
			</div><!-- hmInScrollRow -->
			<div class="clear">&nbsp;</div>
			<div class="readMore"><a href="<?php echo Mage::helper('ekkitab_catalog')->getGlobalSectionViewUrl($section->getSectionId()) ?>">See All...</a></div>
			<div class="clear hmInScrollRowSep"></div>
			<div class="clear"></div>
<?php	} else { //end of if(products not null )... ?>
			<br/>This section will be updated soon...<br/>
<?php	} //end of else ..?>
		</div><!-- hmScrollRow -->
	</div><!-- hmSummerTextImage -->
</div><!-- hmSummerRow -->
<?php endif; ?>
<div class="clear"></div>


