<?php
/**
 * Magento
 *
 * @copyright  Copyright (c) 2009 Ekkitab Educational Services Pvt Ltd (http://www.ekkitab.com)
 *
 * All  Categories List template
 *
 */
?>
<?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
<div class="contentArea">
<div class="pageHeader">Institutes under your administration</div>
<?php
	function getShortenedString($str,$count){
		$resStr = '';
		//$str = eregi_replace(" +", " ", $str);
		$array = explode(" ", $str);
		$arrCount = count($array); 
		if($arrCount >0){
			$count = $count > $arrCount ? $arrCount : $count;
			for($i=0;$i < $count ;$i++)
			{
				$resStr=$resStr." ".$array[$i];
			}
		}
		return $resStr;
	}

	$institutes = $this->getMyInstitutes();
	if(!is_null($institutes) && $institutes->count() > 0 ){
?>
<?php if($this->getLastPageNumber()>1): ?>
<div class="searchResTop">
	<div class="leftArea">
	</div><!-- leftArea -->
	<div class="rightArea">
		<div class="topPaginationArea">
			<ul>
				<?php if (!$this->isFirstPage()): ?>
					<li><a href="<?php echo $this->getPreviousPageUrl() ?>" id="prev"><?php echo $this->__('Prev') ?></a></li>
				<?php else: ?>
					<li class="nolink"><?php echo $this->__('Prev') ?></li>
				<?php endif; ?>
				
				<?php foreach ($this->getPages() as $_page): ?>
					<?php if ($this->isPageCurrent($_page)): ?>
						<li><span><?php echo $_page ?></span></li>
					<?php else: ?>
						<li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
					<?php endif ?>
				<?php endforeach; ?>

				<?php if (!$this->isLastPage()): ?>
					<li><a href="<?php echo $this->getNextPageUrl() ?>"><?php echo $this->__('Next') ?></a></li>
				<?php else: ?>
					<li><b id="sep"><?php echo $this->__('Next') ?></b></li>
				<?php endif; ?>

			</ul>
		</div>
	</div><!-- rightArea -->
	<div class="clear"></div>
</div><!-- searchResTop -->
<?php endif; ?>
<table class="custom-data-table box-table" id="institute-table" cellspacing="0">
		<col width="110"/>
		<col width="300"/>
		<col width="540"/>
		<tbody>
<?	foreach ($institutes as $institute): 
?>	
			<tr>
				<td><img src="<?php echo $this->helper('ekkitab_institute')->resize($institute->getImage(),'small_image',false,90,null); ?>" class="img-border" /></td>
				<td><a href="<?php echo $this->helper('ekkitab_institute')->getViewLink() ?>id/<?php echo $institute->getId() ?>"><?php echo $institute->getName(); ?></a>
				<br/><?php echo $institute->getLocality(); ?>, <?php echo $institute->getCity(); ?>, <?php echo $institute->getState() ?>.
				<br/><a href="<?php echo $institute->getWebsiteUrl(); ?>" target="_blank"><?php echo $institute->getWebsiteUrl()?></a>
				<br/><a href="<?php echo $this->helper('ekkitab_institute')->getEditUrl($institute->getId()); ?>">Edit Institute</a>
				</td>
				<td ><?php $desc = $institute->getAboutus();
				  		   $shortDesc = getShortenedString($desc,30);
						   if(trim($shortDesc) !=''){ ?>
								<?php echo $shortDesc; ?>
					<?php } else{ ?>
							Ekkitab welcomes '<?php echo $institute->getName() ?>' to our Network.
					<?php } ?>
						  ... <a href="<?php echo $this->helper('ekkitab_institute')->getViewLink() ?>id/<?php echo $institute->getId() ?>">read more.</a></td>
			</tr>
<?php	endforeach; ?>
		</tbody>
	</table>
<?php	}else{
?>
		&nbsp; <?php echo $this->__("There are no institutes registered under your administration.") ?>
<?php }
?>
<div class="clear"></div>
</div><!-- allCategoriesArea -->

