<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
include("menuitems.php");
$sec_count = is_array($sections)?count($sections):$sections->count(); 
if($sec_count): 
	foreach ($sections as $section):
		$header = $section['header'];
?>	
		<div class="linkHdr"><?php echo $header?> </div><!-- linkHdr -->
		<ul>

<?php	$link_count = is_array($section['link'])?count($section['link']): 0 ;
		if($link_count > 0 ){
			for ($i=0; $i < $link_count ; $i++) {
				$linkCaption = $section['link'][$i] ;
				$linkUrl = $section['url'][$i];
				$linkUrl = $this->getUrl($linkUrl);
?>				<li><a href="<?php echo $linkUrl ?>"><?php echo $this->htmlEscape($linkCaption) ?></a></li>
<?php		}
		}
?>		</ul><div class="menuSep"></div>
<?php 
	endforeach;
endif; ?>
