<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
global $sections,$books;
require("menuitems.php");
$sec_count = getNumberOfSections();
if($sec_count): 
	$sectionKeys = array_keys($sections);
	foreach ($sectionKeys as $key) :
		$header = getHeader($key);
		$tagEnded = false;
		$startTag="<ul>";
		$endTag="</ul>";
		$columnCount=3;
		$count=0;
		$showAllLink=getShowAllLink($key);
		$showThumbnail=getIsShowThumnail($key);
		$header = getHeader($key);
	    if ($showAllLink !="" ) {
			$header=$header." <span class='seeAllLink'> [<a href='".$this->getUrl($showAllLink)."' title='See All'  >See All</a>] </span>";
		}
	    if ($showThumbnail) {
			$startTag='<table class="menu-data-table">';
			$endTag="</table>";
	    }
?>	
		<div class="linkHdr"><?php echo $header?> </div><!-- linkHdr -->
		<?php echo $startTag ?>
<?php			
		$links = getLinks($key);
		$firstLink = 1;
		foreach($links as $link){
			$linkCaption = ucwords(trim($link['name'])) ;
			if (preg_match("/__by__/", $linkCaption)) {
				$info = explode("__by__", $linkCaption);
				$linkCaption= trim($info[0]);
				$linkAuthor = 'by <span class="author">'.trim($info[1]).'</span>' ;
			}else{
				$linkAuthor="";
			}
			$linkUrl = $link['url'];
			$linkUrl = $this->getUrl($linkUrl);
			if(array_key_exists('image',$link)){	
				$image = $link['image'];
				if($count==0 || $count > $columnCount){
					if(!$firstLink){ echo "</tr>";}
?>					<tr>
<?php				$count=1;
				}
?>				 <td><a href="<?php echo $linkUrl ?>"><img src="<?php echo $this->helper('ekkitab_catalog')->resize($image,'minithumb',false,null, 60); ?>" alt="<?php echo $linkCaption ?>" /></a></td>
<?php			$count++;
			}else {?>
			<li><a href="<?php echo $linkUrl ?>"><?php echo $this->htmlEscape($linkCaption) ?></a><?php  echo $linkAuthor ?></li>
<?php		}
			$firstLink=0;
		}
		if(!$tagEnded){
?>			<?php echo $endTag ?>
<?php	} 
?>	
	<div class="menuSep">&nbsp;</div>
<?php 
	endforeach;
endif; ?>
