<?php
/**
 * 
 * Frontend Global Section Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php	
	function getShortenedString($str,$count){
		$resStr = '';
		//$str = eregi_replace(" +", " ", $str);
		$array = explode(" ", $str);
		$arrCount = count($array); 
		if($arrCount >0){
			$count = $count > $arrCount ? $arrCount : $count;
			for($i=0;$i < $count ;$i++)
			{
				$resStr=$resStr." ".$array[$i];
			}
		}
		return $resStr;
	}

	$linkKey = $this->getLinkKey();
	if($linkKey && strlen(trim($linkKey)) > 0){
		$header	= ucwords(preg_replace('#[_]+#',' ', $linkKey));
?>
		<div class="listPageHeader"><?php echo $header ?></div><!-- listPageHeader -->
<?php	
		$productsArr = getBooksForKey($linkKey);
		$products= $this->getLinkBooks($productsArr);
		$_count = (!is_null($products) && is_array($products))?count($products):(!is_null($products))? $products->count() :0;  
		if(!is_null($products) && $_count > 0){ 
			foreach($products as $book){ 
				$authorArr = $book->getAuthor();
				$author = $authorArr['a'] ;
				$author = strlen($author) > 0 ? $author : "Unknown";
				$title = $book->getTitle();
				$image = $book->getImage();
				$id = $book->getId();
				$listPrice = $book->getListPrice() ;
				$discPrice = $book->getDiscountPrice();
				$isbn = $book->getIsbn();
				$sourcedFrom =  $book->getSourcedFrom();
				if($sourcedFrom && strlen(trim($sourcedFrom)) > 0 && strtolower($sourcedFrom)=='us'){
					$isbn.= " <em>[ Imported Edition ]</em>";
				}
				$shippingTimeMin =(int)$book->getDeliveryPeriod();
				$shippingTimeMax = round($shippingTimeMin + (.5 * $shippingTimeMin) );
				$binding=strlen($book->getBinding()) > 0 ? ucfirst($book->getBinding()) : "Not Available" ;
				$language=strlen($book->getLanguage()) > 0 ? $book->getLanguage() : "Unknown";
				$stock=$book->getInStock();
				$shortDesc=$book->getDescription();
			
				//further alterations.
				$savings= $listPrice - $discPrice;
				$savingsPerct= round(($listPrice >0 )? (($listPrice - $discPrice)/ $listPrice ) * 100 : 0);
				$savingsPerct= $savingsPerct > 5 ? $savingsPerct : 0; 
				$shippingTime = ( $shippingTimeMin > 0 && $shippingTimeMax > 0 ) ? "Delivers in ".$shippingTimeMin." - ".$shippingTimeMax." business days":"";
				$shortDesc= ($shortDesc =="Not Available") ? "" : $shortDesc;
				
				$shortDesc = getShortenedString($shortDesc,30);

				$url=$this->helper('ekkitab_catalog')->getProductUrl($author,$title,$book->getIsbn());	
?>
				<div class="listRow">
				<div class="skuImage"><div class="image"><a href="<?php echo $this->getUrl($url)?>" title="<?php echo $title ?>"><img src="<?php echo $this->helper('ekkitab_catalog')->resize($image,'small_image',false,null, 109); ?>" alt="<?php echo $title ?>" /></a></div></div>
				<!-- skuImage -->
				<div class="detailsArea">
					<div class="bkTitle"><a href="<?php echo $this->getUrl($url)?>"  title="<?php echo $title ?>"><?php echo $title ?></a></div><!-- bkTitle -->
					<div class="lineHeight14em">Author:<?php echo $this->helper('ekkitab_catalog')->getAuthorUrl(null,$author) ?>"></div>
					<div class="lineHeight14em">ISBN: <?php echo $isbn ?></div>
					<div class="lineHeight14em">Binding: <?php echo $binding ?></div>
					<div class="lineHeight14em">Language : <?php echo $language ?> </div>
					<div class="synop"> <?php echo $shortDesc ?>... <a href="<?php echo $this->getUrl($url)?>" title="<?php echo $title ?>">More details</a></div><!-- synop -->
				</div><!-- detailsArea -->

				<div class="priceArea">
				<?php if($savings > 0):?>
					<div class="youSave">Our Price: <?php echo Mage::helper('core')->currency($discPrice,true,false) ?></div>
				<?php endif; ?>
				<?php if($listPrice > 0):?><div class="lineHeight14em">MRP Price : <?php echo Mage::helper('core')->currency($listPrice,true,false) ?></div><?php endif; ?>
				<?php if($savings > 0):?>
					<div class="textArea">
						<div class="youSave">Save <?php echo Mage::helper('core')->currency($savings,true,false) ?></div>
				<?php endif; ?>
				<?php if($listPrice >0) : ?>
					<?php if($stock==1) : ?>
						<div class="lineHeight14em"><?php echo $shippingTime ?></div>
						<div class="youSave">In Stock</div>
					<?php elseif($stock==2): ?>
						<div class="lineHeight14em">Forthcoming Title.</div>
						<div class="youSave">Pre-order.</div>
					<?php else : ?>
						<div class="noStock">Out of Stock </div>
					<?php endif;?>
				<?php else:?>
					<div class="noStock">Out of Stock </div>
				<?php endif;?>
				<?php if($savings > 0):?>
					</div>
					<div class="fsu<?php echo $savingsPerct?>"></div>
					<div class="clear"></div>
				<?php endif; ?>
				</div><!-- priceArea -->
				<div class="clear"></div>

				<!-- div class="listReviewArea"><div class="boldFont">Review</div>
				"I can't believe how good Patterson is, whether he's doing a Washington police yarn or traveling a different road with a female narrator. He is always on the mark. I have never begun a Patterson book and been able to put it down." <div class="boldFont">(USA Today Larry King)</div>
				</div><listReviewArea -->
				
				</div><!-- searchRow -->

<?php		}		//end if for..
		}
		else{ 
			//end of if(products not null )...
?>
		<div class="notFoundArea">
		<ul><li>This section will be updated soon...</li></ul></div>
<?php
		}
	} else { //end of if(linkKey not null )... 
?>
			<div class="hmMainRows">
				<div class="mainLeftHdr">Our Apologies...</div>
				<div class="notFoundArea">
					<p> The content you have requested for is not available.
					<ul>

					<li>If you typed the URL directly, please make sure that the spelling is correct.</li>
					<li>If you clicked on a link to get here, the link might be outdated</li></ul>
					</p>
					<p><div class="boldFont">What can you do?</div>
					Please contact Customer Care at  <a href="mailto:support@ekkitab.com">support@ekkitab.com</a> and let us know of this problem. We appreciate your help in ensuring that the service is available and runs error free.
					<ul>
					<li>Go <a href="javascript:history.back();">back to the previous page</a></li>
					<li>Use the Search Facility at the top of the page to search the ekkitab web site</li>
					<li>Click on any of the links below to get you back on track
					<ul><li><a href="<?php echo $this->getUrl('home')?>">ekkitab Home Page</a></li>
					<li><a href="<?php echo $this->getUrl('customer/account')?>">My Account</a> (You will have to Sign in or Register, if it's your first time)</li>
					</ul>
					</li></ul>
					</p>
				</div><!-- notFoundArea -->
			</div><!-- hmMainRows -->
<?php
	} //end of else ..
?>