<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
$links= $this->getAllLinkItems();
$_count = is_array($links)?count($links):$links->count(); 
$hdr = "";

if($_count): 
	foreach ($links as $link): 

		//$url = $this->helper('ekkitab_catalog')->getLeftLinkUrl($actionMethod,$paramArr);
		$caption = urlencode(preg_replace('#[^A-Za-z0-9\_]+#', '-', $link->getCaption()));
		$url = 'ekkitab_catalog/leftlinks/view/details/'.$caption.'__'.$link->getId().'.html';
		$url = $this->getUrl($url);
		if($hdr=="" || $hdr != trim($link->getHeader())){  
			if($hdr!=""){	?>	
			</ul><div class="clear"></div>
<?php		}
			$hdr = trim($link->getHeader()); 		?>	
			<div class="linkHdr"><?php echo $hdr?> </div><!-- linkHdr -->
			<ul>
<?php	}	?>
		<li><a href="<?php echo $url ?>"><?php echo $this->htmlEscape($link->getCaption()) ?></a></li>
<?php
	endforeach ?>
			</ul>
<?php endif; ?>
