<?php
/**
 * Magento
 *
 * @copyright  Copyright (c) 2009 Ekkitab Educational Services Pvt Ltd (http://www.ekkitab.com)
 *
 * All  Categories List template
 *
 */
?>
<?php
/**
 * Category left navigation
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php $_categories=$this->getStoreCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php if($_count): ?>
<div class="box layered-nav">
	<h4><?php echo $this->__('All Categories') ?></h4>
	<div class="content">
		<div class="narrow-by">
			<dl id="narrow-by-list">
				<dd class="no-padding no-border">
					<ol>
					<?php foreach ($_categories as $_category): ?>
						<?php if($_category->getIsActive()): ?>
							<li>
								<a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="active"<?php endif ?>><?php echo $this->htmlEscape($_category->getName()) ?></a>
							</li>
						<?php endif; ?>
					<?php endforeach ?>
					</ol>
				</dd>
			</dl><script type="text/javascript">decorateDataList('narrow-by-list')</script>
		</div>
	</div>
</div>
<?php endif; ?>
<!-- [ends] .browse-by // -->
