<?php
/**
/**
 * 
 * Frontend Popular Categories Resource Model
 * @category   Local/Ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @package    Local_Ekkitab
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
 ?>
<?php
/**
 * Category left navigation
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>

<?php $_currcategory=$this->getCurrentCategory() ?>
<?php $_categories=$this->getCurrentChildCategories()?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<div class="linkHdr"><?php echo $this->htmlEscape($_currcategory->getName())?></div><!-- linkHdr -->
<?php if($_count): ?>
	<dl id="narrow-by-list">
	<ul>
	<?php foreach ($_categories as $_category): ?>
		<?php if($_category->getIsActive()): ?>
		<li>
			<a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="active"<?php endif ?>><?php echo $this->htmlEscape($_category->getName()) ?></a>
		</li>
		<?php endif; ?>
	<?php endforeach ?>
	</ul></dl>
<script type="text/javascript">decorateDataList('narrow-by-list')</script>
<?php endif; ?>
<div class="seeAll">&nbsp;</div><!-- seeAll -->
<!-- [ends] .browse-by // -->
