<?php
include "setenv.php";

$errorList = Array();
$books = Array();
$save = false;
$update = false;
$filename = '';
$command = '';
$book = Array();
$systemOutput = "";
$supplier = "";
$atLeastOnePreorder=false;

// Task is set or not
if(isset($_GET['task'])) {$task = $_GET['task']; } elseif(isset($_POST['task'])) { $task = $_POST['task']; } else { $task = ""; }

// Make the mandatory check if the catalog work directory is present.
if (!is_dir($catalogWorkDirectory)){
  $errorString = "Mandatory directories missing-$catalogWorkDirectory"; 
  $errorList[] = $errorString;
  $task = "";
}
// Irrespective of the task set the books object.
foreach($columnList as $column) {
   if(isset($_GET[$column])) { $book[$column] = trim($_GET[$column]); } 
   elseif(isset($_POST[$column])) { $book[$column] = trim($_POST[$column]); } 
   else { $book[$column] = ""; }
}
/* If the task is checkIsbn.
*/
if ( $task =="checkIsbn" ) {
  $db = initDatabase($reference_config);
  if ( !empty($book['isbn'] )) {
   $isbn = $book['isbn'];
   $book = getBookDetails($db, $isbn);
   if ( $book != null ) {
     if ( $book['info_source'] == 'Ingrams') {
       $errorString = "ISBN:" . $book['isbn'] 
                      . "is an Ingrams import. Click on the link to see the details <a href=isbncheck.php?isbnno=" 
                      . $book['isbn'] . " >" . $book['isbn'] . "</a>";
       $errorList[] = $errorString;
       $task = "";
       $book = Array();
     } else {
      $update = true;
     }
  } else {
    $book = Array();
    $book['isbn'] = $isbn;
  }
 }
  closeDatabase($db);
} 
elseif ($task == "saveSingleBook" ) {
 $books[] = $book;
 $books = formatValues($books);
 $errorList = validBooks($books);
} // task is saveSingleBook
elseif ($task =="saveMultiBooks" ){
// Save the uploaded file into a location
   $supplier =  strtolower($book['info_source']);
   $fileDateTime = date("YmdHis");
   $uploadedFileName=$catalogWorkDirectory.$supplier."_".$fileDateTime.".txt";  
   $uploadedTmpFileName = $_FILES['uploadedFile']['tmp_name'];
   if(move_uploaded_file($uploadedTmpFileName, $uploadedFileName)) {
     // Load the file into books array 
     $fileHandle = fopen($uploadedFileName, "r");
     // The first line contains the header, ignore it as of now.
     if (!feof($fileHandle)){ $tmpString = fgets($fileHandle); }
     while (!feof($fileHandle)){
      $tmpString = fgets($fileHandle);   
      if ( $tmpString == null ) { break; }
      $books[] = getBookFromStandardUploadFormat($tmpString);
     }
     fclose($fileHandle);
     unlink($uploadedFileName);
     // Format the books
     $books = formatValues($books);
     $errorList = validBooks($books);
   }else {
    $books = Array();
   }
}

if (empty($errorList) && ($task == "saveSingleBook" || $task == "saveMultiBooks")){ 
  $save = true; 
} else {
  $errorList = preg_replace("/\n/", "<br>", $errorList);
}
if ( $save ){
  $counter = 0;
  $newArrivalsFileHandle = null;
  $alreadyPresentCount=0;
  // This db points to the reference database.
  $db = initDatabase($reference_config);
  $dbDev = initDatabase($development_config);
  foreach($books as $book ) {
   if ( $counter == 0 ) {
     $supplier =  strtolower($book['info_source']);
     $fileDateTime = date("YmdHis");
     // Create a file for storing the tmp file and writing it down.
     $filename=$catalogWorkDirectory.$supplier."_".$fileDateTime.".txt";  
     $fileHandle = fopen($filename, "w");
   } else {
   }
   if ( getBookDetails($dbDev, $book['isbn']) != null ) { $alreadyPresentCount++;continue; }
  // Generate Bisac Codes
   $book['bisac_codes'] = getBisacCodes($db, array($book['bisac_codes']));
  // Fill Default Values in the data.
   $book = fillDefaultCatalogValues($book);
   fwrite($fileHandle, bookStringInCatalogFormat($book));
  // Check for pre order and write to the new arrivals stock list format.
   if ( $book['in_stock'] == '2' ) {
     if( $newArrivalsFileHandle == null ) {
       $atLeastOnePreorder = true;
       $newArrivalsFileName = $catalogWorkDirectory.$supplier."-newarrivals-stocklist_".$fileDateTime.".txt";
       $newArrivalsFileHandle = fopen($newArrivalsFileName, "w");
     } 
     fwrite($newArrivalsFileHandle, bookStringInStockFormat($book));
   } // New Arrivals check.
   $counter++;
  } // For all the books.
  fclose($fileHandle);
  if( $newArrivalsFileHandle != null ) fclose($newArrivalsFileHandle);
  closeDatabase($db);
  closeDatabase($dbDev);
  /*Run the import books for the above file. If the value returned by importbooks is same as the book count
    then only append the same to the catalog file else display error 
    NOTE: The import only works againts the development database.
  */
 $command = "php " . $importBooksCode . " -bd IndiaPublisher " . $filename;
 $execOuput = Array();
 exec($command , $execOutput, $retval);
 $execOutput[] = "$command Return value = $retval";
 if( count($books) - $alreadyPresentCount == $retval ) {
   // Append the file data to the catalog
   $command = "cat $filename >> $catalogDirectory/$supplier.txt"; 
   exec($command , $execOutput, $retval);
   $execOutput[] = "$command Return value = $retval";
  // If preorder append the new arrivals to the new-arrivals stocklist
   if($atLeastOnePreorder) {
    $command = "cat $newArrivalsFileName >> $stockDirectory/newarrivals-stocklist.txt"; 
    exec($command , $execOutput, $retval);
    $execOutput[] = "$command Return value = $retval";
   }
  // Reset the books array so that it does not carry the data.
  $book =  null;
  $books = Array();
  $execOutput = Array();
  $execOutput[] = "Success: Book has been successfully added to catalog";
 } else {
  // Do nullify the objects as we do not want the same to be shown up in the single update
  if ( $task == "saveMultiBooks" ) { $book = null; $books = Array(); }
  $execOutput[] = "Failure: Book was not added to catalog";
 }
 //Unlink the files if created. 
} // Save is true

# HTML CODE FROM BELOW
?>
<html>
<head>
 <script src="../js/prototype/prototype.js" type="text/javascript"></script>
 <script type="text/javascript" language="JavaScript">

/* Function to submit the form on tab out */
 function checkIsbn(isbn){
    var input_task = document.getElementById("input_task"); 
    input_task.value='checkIsbn';
    var form_singleBookUpdate = document.getElementById("form_singleBookUpdate");
    form_singleBookUpdate.submit();
 }
/* Function to toggle between divs */
 function toggle(divName){
    var singleDiv = document.getElementById("div_singleBookUpdate"); 
    var multiDiv = document.getElementById("div_multiBookUpdate"); 
    if( divName == 'single') {
       singleDiv.style.display='block';
       multiDiv.style.display='none';
    } else {
       singleDiv.style.display='none';
       multiDiv.style.display='block';
    }
 }
 </script>
</head>
<body>
<?php include "links.html"; ?>
<div id="updates" >
  <h5><?php print_r($execOutput) ; ?></h5>
</div>
<div id="errors">
  <table class="redFont" border="1">
  <?php 
  $counter = 0;
  foreach ($errorList as $error ){
   $counter++;
   echo "<tr><td>";
   echo "$counter . $error";
   echo "</td></tr>";
  }
  ?>
  </table>
</div>
<br>
<table border="1"><tr><td><a href="javascript:toggle('single');">Single Book Catalog Creation</a></td><td>
<a href="javascript:toggle('multi');">Multi Book Catalog Creation.</a>
</td></tr></table>
<div id="div_singleBookUpdate" style="display:block;background-color:#929bb1">
<form id="form_singleBookUpdate" action='bookupdate.phtml' method='post'>
 <table border='0'>
 <tr>
  <td>ISBN:(13 digit)</td>
  <td>
    <div id="isbncheck_div" style="display:block" ></div>
    <input id='isbn_input' type='text' name ='isbn' size='50' maxlength='20' 
           value='<?php if($book) { echo $book['isbn']; } ?>' onblur=javascript:checkIsbn() <?php if($update) { echo 'readonly'; } ?> />
  </td>
 </tr>
 <tr>
  <td>TITLE:</td>
  <td><input type='text' name ='title' size="50" maxlength='255' value='<?php if($book) { echo $book['title']; } ?>' /></td>
 </tr>
 <tr>
  <td>AUTHOR:(FirstName LastName&SecondFirstName SecondLastName)</td>
  <td><input type='text' name ='author' size='50' maxlength='120' value='<?php if($book) { echo $book['author']; } ?>' /></td>
 </tr>
 <tr>
  <td>DESCRIPTION:</td>
  <td><textarea name ='description' rows="4" cols="50" maxlength='2047' /><?php if($book) { echo $book['description']; } ?></textarea></td>
 </tr>
 <tr>
  <td>SOURCE:(Who supplied the catalog)</td>
  <?php if($update) { ?>
  <td>
   <input type='text' name ='info_source' size='30' maxlength='120' value='<?php if($book) { echo $book['info_source']; } ?>' readonly />
  </td>
  <?php } else { ?> 
  <td>
     <select name ='info_source' value=<?php if($book) { echo $book['info_source']; } ?> />
     <?php 
        foreach($supplierList as $key=>$value ) {
          if ( $book && $book['info_source'] == $value ) {
            echo '<option value="' . $key . '"'. " selected>$value</option>";
          } else {
            echo '<option value="' . $key . '"' . ">$value</option>";
          }
        }
     ?>
     </select>
 </td>
 <?php } ?>
 </tr>
 <tr>
  <td>PUBLISHER:(May be different from SOURCE)</td>
  <td><input type='text' name ='publisher' size='50' maxlength='120' value='<?php if($book) { echo $book['publisher']; } ?>' /></td>
 </tr>
 <tr>
  <td>IMPRINT:(Text only)</td>
  <td><input type='text' name ='imprint' size='50' value='<?php if($book) { echo $book['imprint']; } ?>' /></td>
 </tr>
 <tr>
  <td>PRICE:(Numbers only)</td>
  <td><input type='text' name ='list_price' size='50' value='<?php if($book) { echo $book['list_price']; } ?>' <?php if($update) { echo 'readonly'; } ?> /></td>
 </tr>
 <tr>
  <td>CURRENCY:(I,U,P,S only)</td>
  <td>
     <select name ='currency' value='I' />
     <?php 
        foreach($currencyList as $key=>$value ) {
          echo '<option value="' . $key .'"' . (( $book && $book['currency'] == $value ) ? " selected " : "") . ">$value</option>";
        }
     ?>
     </select>
  </td>
 </tr>
 <tr>
  <td>AVAILABILITY:(Available, Not Available, Preorder)</td>
  <td>
     <select name ='in_stock' value="<?php if($book) { echo $book['in_stock']; } ?>"/>
     <?php 
        foreach($availabilityList as $key=>$value ) {
          echo '<option value="' . $key . '"' . (( $book && $book['in_stock'] == $key ) ? " selected " : "") . ">$value</option>";
        }
     ?>
     </select>
     Note: If Preorder is seleted, the stock will be added to New Arrivals. Else no stock information will be generated.
  </td>
 </tr>
 <tr>
  <td>PUBLISHING DATE:(Text only. Do not include / or -)</td>
  <td><input type='text' name ='publishing_date' size='50' maxlength='255' value='<?php if($book) { echo $book['publishing_date']; } ?>' /></td>
 </tr>
 <tr>
  <td>DELIVERY PERIOD:(Text only. Do not include / or -)</td>
  <td><input type='text' name ='delivery_period' size='50' value='<?php if($book) { echo $book['delivery_period']; } ?>' /></td>
 </tr>
 <tr>
  <td>BINDING:(Paperback,Hardcover,Hardback)</td>
  <td>
     <select name ='binding' value='Paperback' />
     <?php 
        foreach($bindingList as $key=>$value ) {
          echo '<option value="' . $key . '"' . (($book && $book['binding'] == $value) ? " selected " : "") . ">$value</option>";
        }
     ?>
     </select>
  </td>
 </tr>
 <tr>
  <td>PAGES:(Number only)</td>
  <td><input type='text' name ='pages' size='50' value='<?php if($book) { echo $book['pages']; } ?>' /></td>
 </tr>
 <tr>
  <td>LANGUAGE:(English Default)</td>
  <td>
     <select name ='language' value='English' />
     <?php 
        foreach($languageList as $key=>$value ) {
          echo '<option value="' . $key . '"' . " > $value </option>";
        }
     ?>
     </select>
  </td>
 </tr>
 <tr>
  <td>WEIGHT:</td>
  <td><input type='text' name ='weight' size='30' value='<?php if($book) { echo $book['weight']; } ?>' /></td>
 </tr>
 <tr>
  <td>DIMENSION:</td>
  <td><input type='text' name ='dimension' size='30' value='<?php if($book) { echo $book['dimension']; } ?>' /></td>
 </tr>
 <tr>
  <td>SHIP-REGION:</td>
  <td><input type='text' name ='shipping_region' size='30' value='<?php if($book) { echo $book['shipping_region']; } ?>' /></td>
 </tr>
 <tr>
  <td>SUBJECT:(Do not include Bisac codes here )</td>
  <td><input type='text' name ='bisac_codes' size='30' maxlength='120' value='<?php if($book) { echo $book['bisac_codes']; } ?>' /></td>
 </tr>
 <tr>
  <td align="right" colspan="2">
  <input type="hidden" name="filename" value='<?php  echo $filename; ?>' />
  <?php if ( $update ) {
       echo "<input id='input_task' type='hidden' name='task' value='updateSingleBook' />";
       echo "<input id='input_submit' type='submit' value='Update Book' />";
     } else {
       echo "<input id='input_task' type='hidden' name='task' value='saveSingleBook' />";
       echo "<input id='input_submit' type='submit' value='Save Book' />";
     }
  ?>
  </td>
 <tr>
</table>
</form>
</div>
<div id="div_multiBookUpdate" style="display:none;background-color:#c8c8c8">
<table>
 <tr>
  <td colspan="3">Tab delimited format should be in this order. Do not include the header row. The columns after description will be ignored<br><br>
   ISBN-TITLE-AUTHOR-SUPPLIER-PUBLISHER-IMPRINT-PRICE-CURRENCY-AVAILABILITY-PUBLISHING_DATE-DELIVERY_PERIOD-BINDING-PAGES-LANGUAGE-WEIGHT-<br>DIMENSION-SHIPPING_REGION-SUBJECT-DESCRIPTION
   <br><br>
  </td>
 </tr>
</table>
<form id="form_multiBookUpdate" enctype="multipart/form-data" action="bookupdate.phtml" method='post'>
 <table border='1'>
 <tr>
  <td>
    <input type="file" name="uploadedFile"/>
  </td>
  <td>
   SOURCE:(Who supplied the catalog)
  </td>
  <td>
     <select name ='info_source' value='' />
     <?php 
        foreach($supplierList as $key=>$value ) {
            echo '<option value="' . $key . '"' . ">$value</option>";
          }
     ?>
     </select>
 </td>
 </tr>
 <tr>
  <td>
    <input type="hidden" name="task" value="saveMultiBooks" />
    <input type="hidden" name="filename" value='<?php  echo $filename; ?>' />
    <input type='submit' value='Upload Catalog File' />
  </td>
 </tr>
</table>
</form>
</div>
</body>
</html>
