<?php
include "setenv.php";

$errorList = Array();
$execOutput = Array();
$update = false;
$ignoreBook = Array();

// Task is set or not
if(isset($_GET['task'])) {$task = $_GET['task']; } elseif(isset($_POST['task'])) { $task = $_POST['task']; } else { $task = ""; }

// Irrespective of the task set the ignore object.
foreach($columnList as $column) {
   if(isset($_GET[$column])) { $ignoreBook[$column] = trim($_GET[$column]); } 
   elseif(isset($_POST[$column])) { $ignoreBook[$column] = trim($_POST[$column]); } 
   else { $ignoreBook[$column] = ""; }
}
$db = initDatabase($reference_config);
/* If the task is checkIsbn.
*/
if ( $task =="checkIsbn" ) {
  if ( !empty($ignoreBook['isbn'] )) {
   $isbn = $ignoreBook['isbn'];
   $ignoreBook = getBookDetails($db, $isbn);
   if ( $ignoreBook == null ) {
    $ignoreBook = Array();
    $ignoreBook['isbn'] = $isbn;
  } 
 }
} 
elseif ($task == "addToIgnoreIsbns" ) {
 // Check if the isbn is valid i.e if 13 or 10 
 if ( $ignoreBook != null  && !empty($ignoreBook['isbn'])
      && !empty($ignoreBook['title'])  && !empty($ignoreBook['author'])
      && !empty($ignoreBook['info_source'] )) {
      $errorList = addToIgnoreIsbns($db, $ignoreBook); 
      if ( $errorList == null && empty($errorList)) {
         $execOutput[] = "Added book to ignore isbn list";
         $ignoreBook = Array();
      } 
 }  else {
   $errorList[] = "All the fields are mandatory";
 }
} // task is addToIgnoreIsbns
elseif ($task == "updateIgnoreIsbnList" ) {
  if(isset($_GET['isbn_checked'])) {$isbnChecked = $_GET['isbn_checked']; } elseif(isset($_POST['isbn_checked'])) { $isbnChecked = $_POST['isbn_checked']; } else { $isbnChecked = null; }
  removeFromIgnoreIsbns($db, $isbnChecked);
}

$ignoreIsbnList = getIgnoreIsbns($db);
closeDatabase($db);

# HTML CODE FROM BELOW
?>
<html>
<head>
 <script src="../js/prototype/prototype.js" type="text/javascript"></script>
 <script type="text/javascript" language="JavaScript">

/* Function to submit the form on tab out */
 function checkIsbn(isbn){
    var input_task = document.getElementById("input_task"); 
    input_task.value='checkIsbn';
    var form_singleBookUpdate = document.getElementById("form_addIgnoreBook");
    form_singleBookUpdate.submit();
 }
 </script>
</head>
<body>
<h1>Ignore Books in the system</h1>
<div id="updates" >
  <h5><?php if ( $execOutput != null && !empty($execOutput)) print_r($execOutput) ; ?></h5>
</div>
<div id="errors">
  <table class="redFont" border="1">
  <?php 
  $counter = 0;
  foreach ($errorList as $error ){
   $counter++;
   echo "<tr><td>";
   echo "$counter . $error";
   echo "</td></tr>";
  }
  ?>
  </table>
</div>
<br>
<div id="div_addIgnoreBook">
<form id="form_addIgnoreBook" action='ignoreisbns.phtml' method='post'>
 <table border='1' cellspacing='0' cellpadding='5'>
 <tr>
  <td>ISBN:(13 digit)</td>
  <td>
    <div id="isbncheck_div" style="display:block" ></div>
    <input id='isbn_input' type='text' name ='isbn' size='50' maxlength='20' 
           value='<?php if($ignoreBook) { echo $ignoreBook['isbn']; } ?>' onblur=javascript:checkIsbn() <?php if($update) { echo 'readonly'; } ?> />
  </td>
 </tr>
 <tr>
  <td>TITLE:</td>
  <td><input type='text' name ='title' size="50" maxlength='255' value='<?php if($ignoreBook) { echo $ignoreBook['title']; } ?>' /></td>
 </tr>
 <tr>
  <td>AUTHOR:(FirstName LastName&SecondFirstName SecondLastName)</td>
  <td><input type='text' name ='author' size='50' maxlength='120' value='<?php if($ignoreBook) { echo $ignoreBook['author']; } ?>' /></td>
 </tr>
 <tr>
  <td>SUPPLIER:(Valid supplier name)</td>
  <?php if($update) { ?>
  <td>
   <input type='text' name ='info_source' size='30' maxlength='120' value='<?php if($ignoreBook) { echo $ignoreBook['info_source']; } ?>' readonly />
  </td>
  <?php } else { ?> 
  <td>
     <select name ='info_source' value=<?php if($ignoreBook) { echo $ignoreBook['info_source']; } ?> />
     <?php 
        foreach($supplierList as $key=>$value ) {
          if ( $ignoreBook && $ignoreBook['info_source'] == $value ) {
            echo '<option value="' . $key . '"'. " selected>$value</option>";
          } else {
            echo '<option value="' . $key . '"' . ">$value</option>";
          }
        }
     ?>
     </select>
 </td>
 <?php } ?>
 </tr>
 <tr>
    <td align="right"> <input id='input_task' type='hidden' name='task' value='addToIgnoreIsbns' /></td>
    <td><input type='submit' value='Add to ignore ISBN List' /></td>
 <tr>
</table>
</form>
</div>
<div id="div_ignoreisbnslist" style="display:block;">
<form  action="ignoreisbns.phtml" method='post'>
 <table border='1' cellspacing='0' cellpadding='5'>
 <tr>
  <td colspan="5">
    <input type="hidden" name="task" value="updateIgnoreIsbnList" />
    <input type='submit' value='Remove Selected from Ignore Books' /></td>
 <tr>
 <tr><td></td><td>ISBN</td><td>TITLE</td><td>AUTHOR</td><td>SUPPLIER</td></tr>
 <?php 
   foreach($ignoreIsbnList as $ignoreBook ) {
    echo "<tr>";
    echo "<td><input id='isbn_checked' type='checkbox' name='isbn_checked[]' value='" . $ignoreBook['id'] . "'></td>";
    echo "<td>" . $ignoreBook['isbn'] . "</td>";
    echo "<td>" . $ignoreBook['title'] . "</td>";
    echo "<td>" . $ignoreBook['author'] . "</td>";
    echo "<td>" . $ignoreBook['info_source'] . "</td>";
    echo "</tr>";
   }
 ?>
</table>
</form>
</div>
</body>
</html>
