<?php
include "setenv.php";
$errorList = Array();
$images = Array();
$pfdImagesDirectory = '';
$command = '';

// Task is set or not
if(isset($_GET['task'])) {$task = $_GET['task']; } elseif(isset($_POST['task'])) { $task = $_POST['task']; } else { $task = ""; }
if(isset($_GET['loadType'])) {$loadType = $_GET['loadType']; } elseif(isset($_POST['loadType'])) { $loadType = $_POST['loadType']; } else { $loadType = ""; }

// Make the mandatory checks
if (!is_dir($imagesWorkDirectory)){
  $errorString = "Mandatory directories missing-$imagesWorkDirectory"; 
  $errorList[] = $errorString;
  $task = "";
}
if ( $task == "load" ) {
  if($loadType == "pdfImage" ){
     $task = "loadPdfFile";
  } else if ( $loadType == "singleImage" ) {
    $task = "loadSingleImage";
  } else if ( $loadType == "zipImage" ) {
    $task = "logZipFile";
  }else {
     $errorList[] = "Please choose a file and the file type";
  }
}
if ( $task == "loadSingleImage") {
   $dateTime = date("YmdHis");
   $tmpImagesDirectory = $imagesWorkDirectory . "$dateTime";
   mkdir($tmpImagesDirectory);
   // Get the file details from the post variables.
   $uploadedFileName = $tmpImagesDirectory . "/". $_FILES['uploadedFile']['name'];
   $uploadedTmpFileName = $_FILES['uploadedFile']['tmp_name'];
   if(move_uploaded_file($uploadedTmpFileName, $uploadedFileName)) {
     if(is_file($uploadedFileName) && filesize($uploadedFileName) > 0 ){
        $image['name'] = $_FILES['uploadedFile']['name'];
        $image['url'] = $uploadedFileName;
        $isbnno = explode(".", $_FILES['uploadedFile']['name']);
        $image['isbn'] = $isbnno[0];
        $images[] = $image;
     }
   } 
}
/* load PDF file */
else if ( $task == "loadPdfFile" ) {
   $dateTime = date("YmdHis");
   $tmpImagesDirectory = $imagesWorkDirectory . "$dateTime";
   mkdir($tmpImagesDirectory);
   // Get the file details from the post variables.
   $uploadedFileName = $tmpImagesDirectory . "/". $_FILES['uploadedFile']['name'];
   $uploadedTmpFileName = $_FILES['uploadedFile']['tmp_name'];
   echo $uploadedFileName . "-" . $uploadedTmpFileName;
   if(move_uploaded_file($uploadedTmpFileName, $uploadedFileName)) {
     // Convert the pdf file to html with images
     $command = "pdftohtml -noframes $uploadedFileName";
     exec($command, $result );
    // Convert all the png files to jpg files.
     $command = "php $EKKITAB_HOME/utils/convertpngtojpg.php $tmpImagesDirectory";
     exec($command, $result );
     $command = "rm $tmpImagesDirectory/*.html";
     exec($command, $result );
     $command = "rm $tmpImagesDirectory/*.png";
     exec($command, $result );
     $command = "rm $tmpImagesDirectory/*.pdf";
     exec($command, $result );
    // Populate the images Array with the filename and the url
    if ($handle = opendir($tmpImagesDirectory)) {
     while (false !== ($file = readdir($handle))) {
        if ($file != "." && $file != "..") {
           $filename = $tmpImagesDirectory . "/". $file;
           if(is_file($filename) && filesize($filename) > 0 ){
              $image['name'] = $file;
              $image['url'] = $filename;
              $image['isbn'] = "";
              $images[] = $image;
           } else {
             unlink($filename);
           }
        }
     }
    closedir($handle);
    } // Open the directory of the images
   } else{
     $errorString = "Error uploading the file";
     $errorList[] = $errorString;
   } // move is unsuccessful.
} // task loadPdfFile
else if ( $task == "saveImages" ){
  if(isset($_GET['tmpImagesDirectory'])) {$tmpImagesDirectory = $_GET['tmpImagesDirectory']; } 
  elseif(isset($_POST['tmpImagesDirectory'])) { $tmpImagesDirectory = $_POST['tmpImagesDirectory']; } else { $tmpImagesDirectory = ""; }

  if(isset($_GET['imageList'])) {$imageList = $_GET['imageList']; } 
  elseif(isset($_POST['imageList'])) { $imageList = $_POST['imageList']; } else { $imageList = null; }

  foreach($imageList as $filename => $isbn) {
    $isbn = trim($isbn);
    if ( $isbn != "" ) {
       rename($tmpImagesDirectory."/$filename", $tmpImagesDirectory."/$isbn.jpg");
    } 
  }
  $command = "php $EKKITAB_HOME/bin/copyimages.php $tmpImagesDirectory";
  system($command, $result);
  $command = "rm -rf $tmpImagesDirectory";
  system($command, $result);
  $loadType = null;
  $task = null;
  $tmpImagesDirectory = null;
} //task saveImages
?>
<html>
<head>
 <script src="../js/prototype/prototype.js" type="text/javascript"></script>
 <script type="text/javascript" language="JavaScript">

/* Function to submit the form on tab out */
 function cancel(){
   location.reload(true);
   return false;
 }
 </script>
</head>
<body>
<?php include "links.html"; ?>
<h4>Load Images ( Staging )</h4>
<ul>
1. Load a single image file<br>
2. Load a zip file containing the images.<br>
Note: All the image names should be 13 digit isbns with extension .jpg<br>
</ul>
<div id="errors">
  <table class="redFont" border="1">
  <?php 
  foreach ($errorList as $error ){
   echo "<tr><td>";
   echo $error;
   echo "</td></tr>";
  }
  ?>
  </table>
</div>
<br>
<?php if ( !empty($images)) { ?>
<div id="div_saveImages">
<form action="loadimages.phtml" method='post'>
 <table border='1'>
 <?php foreach($images as $image) { 
       echo "<tr>";
       echo "<td><img src='". $image['url'] ."' />";
       echo "<input type='text' name='imageList[". $image['name']. "]' value='" . $image['isbn'] . "' />";
       echo "</tr>";
  } ?>
 <tr>
  <td>
    <input type="hidden" name="task" value="saveImages" />
    <input type="hidden" name="tmpImagesDirectory" value="<?php echo $tmpImagesDirectory ?>" />
    <input type='submit' value='Save'/></td>
 <tr>
</table>
</form>
</div>
<?php } else { ?>
<div id="div_loadFile">
<form enctype="multipart/form-data" action="loadimages.phtml" method='post'>
 <table border='0'>
 <tr>
  <td>
    <input type="file" name="uploadedFile"/>
    <input type="radio" name="loadType" value="singleImage"/>Single Image.
    <input type="radio" name="loadType" value="zipImage"/>Zip File Image.
    <!-- input type="radio" name="loadType" value="pdfImage"/>Pdf File Image. -->
    <input type="hidden" name="task" value="load" />
    <input type="hidden" name="tmpImagesDirectory" value="<?php echo $tmpImagesDirectory ?>" />
    <input type='submit' value='Submit' /></td>
 <tr>
</table>
</form>
</div>
<?php }  ?>
</body>
</html>
