<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Error Submission Form</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="robots" content="*"/>
    <link rel="icon" href="skin/<?php echo $store ?>/images/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="skin/<?php echo $store ?>/images/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="skin/<?php echo $store ?>/images/favicon.ico" type="image/x-icon"/>
	<link type="text/css" rel="stylesheet" href="skin/<?php echo $store?>/css/styles.css" media="all" />
	
	<!--[if IE]>
<style type="text/css">
    .head,
    .page-head,
    .page-head-alt,
    .header-top-container,
    .header-top,
    .header-nav-container,
    .header-nav,
    #nav,
    #nav li,
    #nav a,
    .middle,
    .button-set,
    .form-list li,
    .button-container,
    .group-select li,
    .listing-type-list .listing-item,
    .listing-type-list .product-info .product-reviews { zoom:1; }

    .clear {
        display:block;
        clear:both;
        height:0;
        font-size:0;
        line-height:0;
        }
    .quick-access li { padding-right:4px; padding-left:6px;}
    .home-spot { display:inline; }
    .header-top-container { position:relative; }
    #nav ul li.parent { margin-bottom:-3px;}
</style>
<![endif]-->
<!--[if lt IE 7]>
<style text="text/css">
    h1#logo { display:inline; }
    #nav li.parent { margin-bottom:-3px; }
    .group-select .legend { position:relative; zoom:1; }

    /* Min-height for IE */
    .login-box .content { height:180px; }
    .content-box { height:250px; }
    #main { height:400px; }
    .validation-advice { height:15px; }
    .error-msg, .success-msg, .note-msg { height:23px; }
    .base-mini .head h4, .shopping-cart-collaterals h4 { height:16px; }
</style>
<![endif]-->
</head>

<body class="customer-account-create">
<!-- [start] header -->
	<div class="header">
		<div class="logo"><a href="<?php echo $baseUrl?>"></a></div>
    </div>
<!-- [end] header -->
<!-- [start] middle -->
<div class="whiteBg">
		<!-- globalLinks -->
		<div class="globalLinks"><br/>
		</div>
	<div class="wrapper">
		<div class="reportArea">
			<div class="pageHeader"><br/>There has been an error processing your request. Please try again later or contact us at <a href="mailto:support@ekkitab.com">support@ekkitab.com</a><br/><br/></div>
			<div class="clear5"></div>
			<?php if ($showSentMsg): ?>
			<ul class="messages">
				<li class="success-msg">
					<ul>
						<li>Your message was submitted and will be responded as soon as possible. Thank you for reporting.</li>
					</ul>
				</li>
			</ul>
			<?php endif; ?>
			<?php if ($showSendForm): ?>
			<ul class="messages">
				<li class="note-msg">
					<ul>
						<li>We are currently experiencing some technical issues. We apologize for the inconvenience and will contact you shortly to resolve the issue. To help us serve you please fill in the form below.</li>
					</ul>
				</li>
			</ul>
				<?php if ($showErrorMsg): ?>
				<ul class="messages">
					<li class="error-msg">
						<ul>
							<li>Please fill all required fields with valid information</li>
						</ul>
					</li>
				</ul>
				<?php endif; ?>
				<form action="<?php echo "?id={$reportId}&amp;s={$store}" ?>" method="post" id="form-validate">
					<fieldset class="group-select wide">
						<input type="hidden" name="error_hash" value="<?php echo $errorHash ?>"/>
						<h4 class="legend">Personal Information</h4>
						<ul>
							<li>
								<div class="input-box">
									<label for="firstname">First Name <span class="required">*</span></label><br/>
									<input type="text" name="firstname" id="firstname" value="<?php echo $firstName ?>" title="First Name" class="required-entry input-text"/>
								</div>
								<div class="input-box">
									<label for="lastname">Last Name <span class="required">*</span></label><br/>
									<input type="text" name="lastname" id="lastname" value="<?php echo $lastName ?>" title="Last Name" class="required-entry input-text"/>
								</div>
							</li>
							<li>
								<div class="input-box">
									<label for="firstname">Email Address <span class="required">*</span></label><br/>
									<input type="text" name="email" id="email_address" value="<?php echo $email ?>" title="Email Address" class="validate-email required-entry input-text"/>
								</div>
								<div class="input-box">
									<label for="firstname">Telephone </label><br/>
									<input type="text" name="telephone" id="telephone" value="<?php echo $telephone ?>" title="Telephone" class="input-text"/>
								</div>
							</li>
							<li>
								<div class="input-box">
									<label for="firstname">Comment </label><br/>
									<textarea style="width: 525px; height: 120px;" name="comment"><?php echo $comment ?></textarea>
								</div>
							</li>
						</ul>
					</fieldset>
					<div class="button-set">
						<p class="required">* Required Fields</p>
						<button name="submit" class="form-button" type="submit"><span>Submit</span></button>
					</div>
				</form>
			<?php endif; ?>
			<?php if ($action != 'print'): ?>
				<div style="padding:10px; border:1px solid #666; background:#EFEFEF;text-align:left">
					<div style="width:100%; overflow:auto;text-align:left">
				<pre>
<?php echo $reportData[0] ?>

<b>Trace:</b>
<?php echo $reportData[1] ?>
				</pre>
					</div>
				</div>
			<?php endif; ?>
	</div>

<!-- [start] footer -->
	<div class="footerTop"></div><!-- footerTop -->
	<div class="footerMid">
		<a href="<?php echo $baseUrl?>ekkitab-vision/" title="About Us" >About Us</a>  |                             <a href="<?php echo $baseUrl?>help/" title="Help" >Help</a>  |                             <a href="<?php echo $baseUrl?>privacy-policy/" title="Privacy Policy" >Privacy Policy</a>  |                             <a href="<?php echo $baseUrl?>terms/" title="Terms of Use" >Terms and Conditions</a>  |                             <a href="<?php echo $baseUrl?>ekkitab_catalog/search/fullcatalog/" title="Catalog" >Catalog</a>  |                             <a href="<?php echo $baseUrl?>contacts/" title="Contact Us" >Contact Us</a>             		
		<div class="dottedLine"></div>
		<p>&copy; 2009-10 Ekkitab Educational Services Pvt Ltd. All Rights Reserved.</p>
		</div><!-- footerMid -->
	<div class="footerBot"></div>
<!-- [end] footer -->
</div>
</body>
</html>


