use reference;

--
-- Seed data for table `ek_currency_conversion`
--

insert into ek_currency_conversion (`currency`, `conversion`) values ('USD', 50.0), ('INR', 1.0), ('BPS', 80.0);

--
-- Seed data for table `ek_discount_setting`
--

insert into ek_discount_setting (`info_source`, `discount_percent`) values ('Ingrams', 20), ('1ktestdata', 30), 
                                                                           ('Penguin', 25), ('Unknown', 25);

--
-- Seed data for table `ek_supplier_params`
--

insert into ek_supplier_params (`info_source`, `publisher`, `supplier_discount`, `delivery_period`) values 
                               ('Penguin', 'Alistair Sawday', 20, 5),
                               ('Penguin', 'Allen Lane', 20, 5),
                               ('Penguin', 'Arkana', 20, 5),
                               ('Penguin', 'Alpha', 20, 5),
                               ('Penguin', 'Ace', 20, 5),
                               ('Penguin', 'Avery', 20, 5),
                               ('Penguin', 'A & C Black', 20, 5),
                               ('Penguin', 'Allison & Busby', 20, 5),
                               ('Penguin', 'Atlantic', 20, 5),
                               ('Penguin', 'Blue Hen', 20, 5),
                               ('Penguin', 'BBC', 20, 5),
                               ('Penguin', 'BH Asia', 20, 5),
                               ('Penguin', 'Berkley', 20, 5),
                               ('Penguin', 'Bloomsbury', 20, 5),
                               ('Penguin', 'Claremont', 20, 5),
                               ('Penguin', 'Columbia', 20, 5),
                               ('Penguin', 'Chamberlain Bros', 20, 5),
                               ('Penguin', 'Consumer Guide', 20, 5),
                               ('Penguin', 'Dorling Kindersley', 20, 5),
                               ('Penguin', 'Daedalus Books', 20, 5),
                               ('Penguin', 'Daw', 20, 5),
                               ('Penguin', 'Dutton', 20, 5),
                               ('Penguin', 'Dial', 20, 5),
                               ('Penguin', 'Fig Tree', 20, 5),
                               ('Penguin', 'Faber', 20, 5),
                               ('Penguin', 'GreenWood', 20, 5),
                               ('Penguin', 'Galaxy Press', 20, 5),
                               ('Penguin', 'Granta', 20, 5),
                               ('Penguin', 'Gotham', 20, 5),
                               ('Penguin', 'Grossett', 20, 5),
                               ('Penguin', 'HP Books', 20, 5),
                               ('Penguin', 'Hudson Street', 20, 5),
                               ('Penguin', 'Hamish Hamilton', 20, 5),
                               ('Penguin', 'HardWired', 20, 5),
                               ('Penguin', 'Helicon', 20, 5),
                               ('Penguin', 'Hay House', 20, 5),
                               ('Penguin', 'Jove', 20, 5),
                               ('Penguin', 'John Murray Firm', 20, 5),
                               ('Penguin', 'Kyle Cathie', 20, 5),
                               ('Penguin', 'LadyBird', 20, 5),
                               ('Penguin', 'Library Of America', 20, 5),
                               ('Penguin', 'Lantern', 20, 5),
                               ('Penguin', 'Michael Joseph', 20, 5),
                               ('Penguin', 'Marshall Cavendish', 20, 5),
                               ('Penguin', 'Millennium House', 20, 5),
                               ('Penguin', 'Misc-Unknown', 20, 5),
                               ('Penguin', 'Nal', 20, 5),
                               ('Penguin', 'Orion', 20, 5),
                               ('Penguin', 'Onyx', 20, 5),
                               ('Penguin', 'Overlook', 20, 5),
                               ('Penguin', 'PortoBello', 20, 5),
                               ('Penguin', 'Picus Books', 20, 5),
                               ('Penguin', 'Penguin', 20, 5),
                               ('Penguin', 'Pelham', 20, 5),
                               ('Penguin', 'Peng Mod Classics', 20, 5),
                               ('Penguin', 'Peng Tcc Classics', 20, 5),
                               ('Penguin', 'Picture Puffin', 20, 5),
                               ('Penguin', 'Puffin', 20, 5),
                               ('Penguin', 'Perigee', 20, 5),
                               ('Penguin', 'Philomel', 20, 5),
                               ('Penguin', 'Pi Press', 20, 5),
                               ('Penguin', 'Plume', 20, 5),
                               ('Penguin', 'Portfolio', 20, 5),
                               ('Penguin', 'Prentice Hall', 20, 5),
                               ('Penguin', 'Price Stern Sloan', 20, 5),
                               ('Penguin', 'Putnam', 20, 5),
                               ('Penguin', 'Rough Guides', 20, 5),
                               ('Penguin', 'RazorBill', 20, 5),
                               ('Penguin', 'RiverHead', 20, 5),
                               ('Penguin', 'Roc', 20, 5),
                               ('Penguin', 'Signet', 20, 5),
                               ('Penguin', 'Sort Of Books', 20, 5),
                               ('Penguin', 'Short Books', 20, 5),
                               ('Penguin', 'Sentinel', 20, 5),
                               ('Penguin', 'Tarcher', 20, 5),
                               ('Penguin', 'Time Out', 20, 5),
                               ('Penguin', 'Viking', 20, 5),
                               ('Penguin', 'Warne', 20, 5),
                               ('Penguin', 'Which Books', 20, 5),
                               ('Penguin', 'Wisden', 20, 5),
                               ('Jaico', 'Jaico Publishing House', 20, 5),
                               ('Jaico', 'McGraw-Hill', 20, 5),
                               ('Roli', 'Phaidon', 20, 5),
                               ('', 'Pan MacMillan', 20, 5),
                               ('', 'Parragon Pub', 20, 5),
                               ('', 'Outlook Publishing', 20, 5),
                               ('', 'Simon & Schuster', 20, 5),
                               ('', 'Lonely Planet', 20, 5),
                               ('', 'MacMillan', 20, 5),
                               ('', 'Harper Collins', 20, 5),
                               ('', 'HarperCollins Publishers', 20, 5);
