-- use reference;
-- select "deleting books that have no author and title ...";
-- select "may take a few minutes on a large database ...";
-- delete from books where author is null and title is null;
-- select "deleting books that have no list price ...";
-- select "may take a few minutes on a large database ...";
-- delete from books where list_price is null;
use ekkitab_books;
drop table if exists books;
select "Copying books table from reference to ekkitab_books ...";
create table books like reference.books;
insert into books select * from reference.books where title is not null;
drop table if exists books_promo;
select "Copying books_promo table from reference to ekkitab_books ...";
create table books_promo like reference.books_promo;
insert into books_promo select * from reference.books_promo;
