export JAVA_HOME=/usr/lib/jvm/java-6-sun
export EC2_HOME=$EKKITAB_HOME/ec2-api-tools-1.3-53907
export PATH=$EC2_HOME/bin:$PATH
export EC2_PRIVATE_KEY_DIR=$EKKITAB_HOME/amazonservers/staging/aws
export EC2_CERT="$EC2_PRIVATE_KEY_DIR/cert-JB4RBXST5UWSLRLFLF5CG3DCMIDKAJVJ.pem"
export EC2_PRIVATE_KEY="$EC2_PRIVATE_KEY_DIR/pk-JB4RBXST5UWSLRLFLF5CG3DCMIDKAJVJ.pem"
export AWS_ACCESS_KEY="AKIAJ2THJTEXOIKNZCVA"
export AWS_SECRET_ACCESS_KEY="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"
