#!/usr/bin/perl
use Net::POP3;
use MIME::Parser;

my $validsuppliers = "westland  ";
my $validextns = "zip xls";

my $tmpdir = "/mnt4/publisherdata/stock/autoprocess";
my $targetdir = "/mnt4/publisherdata/stock/xl";

$pop = Net::POP3->new('pop.secureserver.net', Timeout => 60);

if ($pop->login('autostockprocess@ekkitab.com', 'eki22Ab') > 0) {
    my $msgnums = $pop->list; # hashref of msgnum => size
    foreach my $msgnum (keys %$msgnums) {
        my $headerarray =  $pop->top($msgnum);
        my $header = join "", @$headerarray;
        my ($supplier) = $header =~ /Subject: (.*)/m;
        next unless ($validsuppliers =~ /$supplier/i);
        my $msg = $pop->get($msgnum);
        my $parser = new MIME::Parser;
        $parser->output_dir($tmpdir);
        my $entity = $parser->parse_data($msg);
        my @msgparts = $entity->parts;
        foreach my $msgpart (@msgparts) {
            # determine the path to the file in question.
            my $path = ($msgpart->bodyhandle) ? $msgpart->bodyhandle->path : undef;
            # move on if it's not defined,
            # else, figure out the extension.
            next unless $path; 
            $path =~ /[\w\s]+\.([^.]+)$/;
            my $extn = $1; 
            next unless $extn;
            # we only continue if our extension is correct.
            unless ($validextns =~ /$extn/) {
               print "[Info] Removing unexpected filetype ($ext): $path\n";
               unlink $path or print "[Error] Cannot remove file at $path: $!.";
               next; 
            }
            my $destdir = $targetdir . "/" . lc($supplier);
            $command = "cp $path $destdir";
            if ($extn eq "zip") {
                $command = "unzip -d  $destdir $path >/dev/null 2>&1";
            }
            eval { system($command); }; 
            if ($@) {
               print "[Error] $@\n";
               next;
            }
            else {
               unlink $path or print "[Error] Cannot remove file at $path: $!.";
            }
            # remove misc files generated by mime parser.
            $command = "rm $tmpdir/*.html $tmpdir/*.txt";
            eval { system($command); }; 
            print "[Warning] Could not delete misc files from work directory. $@\n" if ($@);
        }
        print "[Info] Processed stock list for $supplier\n";
        # $pop->delete($msgnum);
    }
}

$pop->quit;
