#!/usr/bin/perl
use Net::POP3;
use MIME::Parser;

my $validsuppliers = "-westland-indiabooks-rupa-amit-bookworldenterprises-dolphin-";
$validsuppliers .= "-eurokids-hachette-harpercollins-harvard-harvardbusiness-jaico-";
$validsuppliers .= "-mediastar-newindiabooksource-orientblackswan-oxford-paragonbooks-pearsoneducation-";
$validsuppliers .= "-penguin-philearning-popularprakasham-prakash-prism-pustak-randomhouse-researchpress-sage-schand-";
$validsuppliers .= "-scholasticindia-tarladalalbooks-tbh-vinayaka-wiley-";
my $validextns = "zip xls";

my $tmpdir = "/mnt4/publisherdata/stock/autoprocess";
my $targetdir = "/mnt4/publisherdata/stock/xl";

$pop = Net::POP3->new('pop.secureserver.net', Timeout => 60);

if ($pop->login('autostockprocess@ekkitab.com', 'eki22Ab') > 0) {
    my $msgnums = $pop->list; # hashref of msgnum => size
    foreach my $msgnum (keys %$msgnums) {
        my $headerarray =  $pop->top($msgnum);
        my $header = join "", @$headerarray;
        my ($supplier) = $header =~ /Subject: (.*)/m;
        $supplier =~ s/[\[\]]//g;
        $supplier =~ s/\s//g;
        if (!($validsuppliers =~ /-$supplier-/i)) {
            print "[Warning] Unrecognized supplier: '$supplier'. Ignoring.\n";
            next; 
        }
        my $msg = $pop->get($msgnum);
        my $parser = new MIME::Parser;
        $parser->output_dir($tmpdir);
        my $entity = $parser->parse_data($msg);
        my @msgparts = $entity->parts;
        foreach my $msgpart (@msgparts) {
            # determine the path to the file in question.
            my $path = ($msgpart->bodyhandle) ? $msgpart->bodyhandle->path : undef;
            # move on if it's not defined,
            # else, figure out the extension.
            next unless $path; 
            $path =~ /[\w]+\.([^.]+)$/;
            my $extn = $1; 
            next unless $extn;
            # we only continue if our extension is correct.
            unless ($validextns =~ /$extn/i) {
               # print "[Info] Removing unexpected filetype ($extn): $path\n";
               unlink $path or print "[Error] Cannot remove file at $path: $!.";
               next; 
            }
            my $destdir = $targetdir . "/" . lc($supplier);
            my $targetfile = $path;
            $targetfile =~ s/\s/\\ /g;
            $command = "cp $targetfile $destdir";
            if ($extn eq "zip") {
                $command = "unzip -u -o -d  $destdir $targetfile >/dev/null 2>&1";
            }
            eval { system($command); }; 
            if ($@) {
               print "[Error] $@\n";
               next;
            }
            else {
               unlink $path or print "[Error] Cannot remove file at $path: $!.";
            }
            # remove misc files generated by mime parser.
            $command = "rm -f $tmpdir/*.html $tmpdir/*.txt";
            eval { system($command); }; 
            print "[Warning] Could not delete misc files from work directory. $@\n" if ($@);
        }
        print "[Info] Processed stock list for '$supplier'.\n";
        $pop->delete($msgnum);
    }
}

$pop->quit;
