<?php
/**
 * 
 * Frontend About Us page.
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>

<div class="aboutUsArea">
	<div class="pageHeader">About ekkitab</div>
	<div class="abtTextArea">
		<p>Ekkitab Educational Services Pvt. Ltd. was founded in 2009 and is headquartered in Bangalore, India.</p>
		
		<p><em>Ekkitab is founded on the desire to promote reading. It is based on the belief that every child and adult in India should have access to good books irrespective of where they live and their level in society.</em></p>
		
		<p>To achieve this objective, Ekkitab is putting up a globally accessible book store that carries English and all Indian language books. The immediate goal is to make this on-line bookstore very successful by virtue of good design, easy access and comprehensive stocking.</p>
		
		<p>Ekkitab will<span class="boldFont"> actively promote organizations</span> that are centers of learning, like schools, colleges, city, town and village libraries, by inviting its visitors to donate to these organizations. The company wishes to encourage readership by making good books available easily and by making community reading centers like city and town libraries active and popular by virtue of having good content.</p>
		
		<p>Ekkitab wants to<span class="boldFont"> create the largest donor network of books</span> in the country and thereby realize its vision of providing every Indian with access to good books. This donor network will be driven by goodwill, community and a sense of commitment to the cause that Ekkitab is working towards. We hope to solve the difficulties that exist today for people to share good books and promote reading.</p>
		
		<p>In the process of achieving its vision, Ekkitab hopes to become the best known and best loved brand in bookshops, on-line or otherwise. We hope to be able to take the bookstore and the concept of on-line buying to smaller towns and villages across the country. Eventually, we hope to increase readership and the sheer size of the book business in India. We hope to be able to work with publishers and distributors in the country to help increase access to every book that is in print. This will help the publishing industry by extending their reach across the country and will help readers by decreasing the cost of books.</p>
		
		<p>We hope to become an important channel for publishers to reach their customers and are willing to work with them to build new digital models of commerce that can provide conveniences that are not possible today. In making the business a success we hope to stimulate the donor network to give liberally to the cause of reading in India and to reduce the digital divide between the rich and the poor.</p>
		
		<p>We also hope that by doing so, we can remove the bane of piracy from the industry and ensure that the benefits of each sale reaches its rightful owners. In the longer term, Ekkitab wants to promote good writers and provide a platform for publishers to promote new authors and their works. In everything, we want to support and nourish the book eco-system in the country by scaling it manifold across the Indian population.</p>
		
		<p>Thank you for your interest.</p>
		
		<div class="boldFont">Team Ekkitab</div>
	</div>
	<div class="excerptArea">
		<div class="boldFont">We hope that you have a pleasant experience at www.ekkitab.com and we count on your support of the cause.</div>
		
		<p>You can reach us at: <a href="mailto:support@ekkitab.com">support@ekkitab.com</a></p>
		
		<p>We are located at:<br />#82/83, Borewell Road,<br />Whitefield Main, <br />Bangalore - 560066.</p>
	</div>
	<div class="clear"></div>
</div><!-- aboutUsArea -->