<?php
/**
 * 
 * Frontend Build Version Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php
$file = 'productionsite';
if(!file_exists($file)){ ?>
<div class="left version"><MARQUEE WIDTH=100%>This is not our production site ..Please visit us at www.ekkitab.com</marquee></div>
<?php } ?>
