<div class="rightHdr">In Focus</div>
<div class="tagoreHdr"><i>Meet <span class="largerFont">Sonia Shah</span> -<br/>investigative journalist and critically acclaimed author and world citizen.</i></div>
<div class="tagoreArea">
	<img src="<?php echo $this->getSkinUrl('/images/soniashah.jpg')?>" />
	Ekkitab is delighted to bring you excerpts of an interview with Sonia 
Shah. <br/>She is the winner of several awards and is a frequent and much 
sought after speaker on current affairs and political conferences 
around the world.<br/> Born in the United States, of Indian descent and a 
citizen of the United States and Australia, she grew up in a heady 
cultural mix of the West and the East. <br/> <div class="newsReadMore"><a href="<?php echo $this->getUrl('meet-sonia-shah') ?>">Read the full interview 
and buy her books here...</a></div>
</div>
<!--div class="rightHdr">In Focus</div>
<div class="tagoreHdr">Celebrating the 150<sup>th</sup> year of 
	<span class="largerFont">Rabindranath Tagore's</span> birth anniversary
</div>
<div class="tagoreArea">
	<div class="face">
		<img src="<?php echo $this->getSkinUrl('/images/tagore_face.jpg')?>" />
	</div>
	Where the mind is without fear
	and the head is held high,<br />
	Where knowledge is free;<br />
	Where the world has not been broken 
	up into fragments by narrow domestic
	walls;<br />
	 Where words come out from the
	depth of truth;<br />
	Where tireless striving<br />
	stretches its arms towards<br />
	perfection;<br />
	Where the clear stream of reason
	has not lost its way<br /> into the
	dreary desert sand of dead habit;<br />
	Where the mind is led forward 
	by thee into ever-widening 
	thought and action-<br />
	into that heaven of freedom,
	my Father,<br />
	Let my country awake.<br />
	<div class="newsReadMore"><a href="<?php echo $this->getUrl('ekkitab_catalog/search/index/q/Rabindranath Tagore')?>">Books on Tagore</a></div>
</div-->
