<!--<div class="tagoreHdr"><span class="orangeItTxt12"><i>Author Focus: </i><br></span><span style="font-size:11px;font-weight:bold;float:right;color:#c60">Rohintin Mistry</span><br/></div>-->
<div class="tagoreHdr"><span class="orangeItTxt12"><i>Author Focus</i><span style="float:right"><br>Rohinton Mistry</span></span></div>
<div class="tagoreArea">
	<a href="<?php echo $this->getUrl('books/rohintonmistry.html')?>"<img height="250px" src="<?php echo $this->getSkinUrl('/images/rohintonmistrycollage.jpg')?>" /></a><br>Rohinton Mistry was born in Mumbai and left India for Canada at the age of 23. His book, "Such a long Journey" has been the subject of controversy ever since it was trashed by the Shiv Sena in Mumbai and subsequently withdrawn from the Mumbai University syllabus, although it was a strong contender for the Booker Prize and was made into a movie in 1998. <br>His books, portray diverse facets of Indian socioeconomic life; as well as Parsi Zoroastrian life, customs, and religion and are intensely nostalgic on India.

<br/>New editions of his <a href="<?php echo $this->getUrl('books/rohintonmistry.html')?>">books from Penguin India</a> are available for online purchase. Our online bookstore delivers books free to your doorstep anywhere in India.<br>
</div>
