<div> Follow us on : &nbsp; 
	<a href="http://www.facebook.com/ekkitab" target="_blank" rel="nofollow external"><img src="<?php echo $this->getSkinUrl("images/facebook.png")?>" align="absmiddle"/></a> 
	<a href="http://blog.ekkitab.com" target="_blank" style="margin: 0px 0px 0px 5px;" ><img src="<?php echo $this->getSkinUrl("images/blog.jpg")?>" title="Ekkitab Blog" align="absmiddle"/></a> 
</div>
<div class="menuSep"></div>
<div class="padderTop5px" ><a href="<?php echo $this->getUrl('ekkitab_content/index/overleaf/product/beam.html') ?>" ><img src="<?php echo $this->getSkinUrl("images/overleaf_beam.gif")?>" align="absmiddle"/></a></div>
<div class="menuSep"></div>