<div class="topRow">		
	<div class="textArea">
		<div class="mainHdr">Enabling a billion readers</div>
		<img src="<?php echo $this->getSkinUrl("images/hm_top_bks.jpg") ?>" />
		In a country of a billion people, how do we feel about belonging to that privileged group of a few million who can read? How would things change if more people could read? And what does it take to make that happen? A daunting set of issues that quite possibly requires every one of us to help in our own ways. We founded Ekkitab as a vehicle to achieve that vision. We believe that each of us, who are interested in books, can make a difference, if we are connected together and can help without extraordinary effort. At Ekkitab, we are just starting out and are putting together the basics of the structure that will enable this inter-connectedness that will allow each of us to contribute to this larger goal. We hope you will like the purpose and the plan and will join us in enabling a billion readers to bloom in our country...	<a href="ekkitab-donation-home">Read more &raquo;</a>		
		<div class="readMore"></div>
		<!-- raedMore -->		
	</div><!-- textArea -->
</div><!-- topRow --> 