<div class="donateArea">
	<div class="pageHeader">Ekkitab Vision</div>
		<div class="abtTextArea">

		<p>
		Ekkitab's goal is to bridge this divide between the haves and have-nots of our society. Our mission is to enable a billion readers across India by providing them easy access to cheap, affordable books.</p>

		<img src="<?php echo $this->getSkinUrl("images/hm_top_bks.jpg") ?>" />
		<p>Each of us - you, dear reader, and we, who have founded this company and created this website - is privileged indeed. Our education and literacy has enabled us to establish a strong foundation to realize our professional & personal dreams. 

		<p>
		Ekkitab is a vision founded on the belief that we can make a monumental impact on society by combining our individual capabilities and resources. Ekkitab wants to build a network of literary enthusiasts who will help spread literacy and create more readers across India by not only purchasing books for themselves, but also contributing books to others less fortunate. As a website, we hope to play a pivotal role in establishing this network and facilitating the process of channeling resources to places & institutions that require our support.

		<p>
		The name Ekkitab stands for "one book". Philosophically, it represents our effort to change the status quo, one book at a time. It also enshrines our goal of trying to put at least one book in every reader's hands.

		<p>
		Our bookstore is just a starting point for generating resources to fuel our efforts. We hope you will find the bookstore enjoyable to visit and to purchase from. We will do our best to keep the content fresh so that you will find something new every time you visit us. We will ensure that our service never disappoints you and we will do our best to stock our store with all the books that you will ever want to browse or buy.

		<p>
		We are not quite ready yet with everything. This bookstore is still a work in progress. We are working very hard to put the right mechanisms in place to help us achieve our vision: Enabling a Billion Readers. We will continue to update you with our progress as we build the pieces that will enable our network to function. The Ekkitab community hopes we have your support because we cannot succeed without you. If you would like to help us and be part of the mission, please let us know by sending us an email at: <a href="mailto:icanhelp@ekkitab.com">icanhelp@ekkitab.com</a>

		<p>
		Sincerely,<br/>
		Team Ekkitab<br/>
		Ekkitab Educational Services Pvt. Ltd.<br/>
		Founded:  2009<br/>
		Located:  Bangalore	<br/>
	</div><!-- abtTextArea -->
	<div class="clear"></div>
</div><!-- donateArea --> 