<?php
/**
 * 
 * Frontend Build Version Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="donateAreaIn">
<div class="linkHdr">Enabling a billion readers</div><!-- linkHdr -->
<div class="text"><img src="<?php echo $this->getSkinUrl("images/donate_bks_small.jpg") ?>" />Some text explaining the "Donate a book" concept will come here. How to concept  to donate etc...</div>
</div><!-- donateAreaIn -->
<div class="seeAll"><a href="#">Read more &raquo;</a></div><!-- seeAll -->
