<div class="donateArea">
	<div class="pageHeader">Ekkitab Vision</div>
		<div class="abtTextArea">

		<p>
		Our country has a great literary legacy and we continue to produce great writers and poets in the myriad of languages that are our mother tongues. But this inheritance is limited to those of us who are fortunate to be literate and can read and enjoy and learn from the books around us. Those of us who cannot, are like the children of a lesser god, unaware of (and unable to accept) the gift of knowledge that comes with books and the ability to read.
		</p>

		<img src="<?php echo $this->getSkinUrl("images/hm_top_bks.jpg") ?>" />
		<p>Each of us - you, dear reader, and we, who have founded this company and created this website - are privileged indeed. We can read and have benefited hugely by being able to do so and have advanced our stations in life. Ekkitab is a vision founded on the belief that we can achieve much, by combining our individual abilities in such a way that our combined effort and results can be monumental. A network of readers who help create more readers across the country by each giving a little of their resources. As a website, we hope to play a pivotal role in establishing this network and mentoring the process of channeling resources to the places that require support. 

		<p>
		The name Ekkitab stands for "one book". Philosophically, it represents our effort to change the status quo, one book at a time. It also enshrines our goal of trying to put at least one book in every reader's hands.

		<p>
		Our bookstore is a starting point in this scheme of things. It is a means of generating the resources that this effort requires. We hope you will find the bookstore enjoyable to visit and to buy from. We will do our best to keep the content fresh so that you will find something new everytime you visit us. We will ensure that our service never disappoints you and we will do our best to stock our store with all the books that you will ever want to browse or buy. 

		<p>
		We are not quite ready yet with everything. This bookstore is still a work in progress for our vision to enable a billion readers. We will keep you informed of our progress as we build the pieces that will enable the network to function. We hope we have your support because we cannot succeed without you. If you would like to help us and be part of the mission, please let us know by sending us an email at: <a href="mailto:icanhelp@ekkitab.com">icanhelp@ekkitab.com</a>

		<p>
		Sincerely,<br/>
		Team Ekkitab

		<p>
		Ekkitab Educational Services Pvt. Ltd.<br/>
		Founded:  2009<br/>
		Located:  Bangalore	<br/>
	</div><!-- abtTextArea -->
	<div class="clear"></div>
</div><!-- donateArea --> 