<div class="donateAreaRight">
<div class="linkHdr">Enabling a billion readers</div><!-- linkHdr -->
<div class="text"><a href="<?php echo $this->getUrl('ekkitab-vision')?>"><img src="<?php echo $this->getSkinUrl("images/donate_bks_small.jpg") ?>" alt="Donate Books via Ekkitab - the online Indian bookstore" title="Donate Books via Ekkitab - the online Indian bookstore" /></a>
	As an online bookstore in India, we feel privileged to be able to run a donation network that will drive the gift of new books to those who need them. Please visit the <a href="<?php echo $this->getUrl('ekkitab_institute/search/listall')?>" style="text-decoration:underline">schools in our network to <strong>donate</strong></a>. <br/>Please <a href="<?php echo $this->getUrl('ekkitab_institute/account/create')?>" style="text-decoration:underline">click here to join <strong>our network</strong></a>.<div class="menuSep"></div></div><!-- seeAll -->
</div><!-- donateAreaIn -->

<!--div class="topRow">		
	<div class="textArea">
		<div class="mainHdr">Enabling a billion readers</div>
		<img src="<?php echo $this->getSkinUrl("images/hm_top_bks.jpg") ?>" />
		In a country of a billion people, how do we feel about belonging to that privileged group of a few million who can read? How would things change if more people could read? And what does it take to make that happen? A daunting set of issues that quite possibly requires every one of us to help in our own ways. We founded Ekkitab as a vehicle to achieve that vision. We believe that each of us, who are interested in books, can make a difference, if we are connected together and can help without extraordinary effort. We hope you will like the purpose and will join us in enabling a billion readers to bloom in our country... <a href="<?php echo $this->getUrl('ekkitab-vision')?>">Read more &raquo;</a>
		<div class="readMore"></div>
	</div>
</div--> 
