<?php
/**
 * 
 * Frontend Quick search Block
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="globalLinks">
<a href="#">Great Bargains</a> | <a href="#">Top Books of the Month</a> | <a href="#">Top Books of 2009</a> | <a href="#">Top Children's Books</a> | <a href="#">Top Authors</a> | <a href="#">Best Indian Books</a>
</div>