<?php
/**
 * 
 * Frontend Customer Service page.
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="aboutUsArea">

<div class="page-head"> <h3>Customer Service</h3> </div>

<ul class="disc" style="margin-bottom:15px;">
	<li><a href="#answer1">Shipping & Delivery</a></li>
	<li><a href="#answer2">Privacy & Security</a></li>
	<li><a href="#answer3">Returns & Replacements</a></li>
	<li><a href="#answer4">Ordering</a></li>
	<li><a href="#answer5">Payment, Pricing & Promotions</a></li>
	<li><a href="#answer6">Viewing Orders</a></li>
	<li><a href="#answer7">Updating Account Information</a></li>
</ul>
<dl>
	<dt id="answer1">Shipping & Delivery</dt>
	<dd style="margin-bottom:10px;">To be updated.</dd>
	
	<dt id="answer2">Privacy & Security</dt>
	<dd style="margin-bottom:10px;"></dd>
	
	<dt id="answer3">Returns & Replacements</dt>
	<dd style="margin-bottom:10px;">To be updated</dd>
	
	<dt id="answer4">Ordering</dt>
	<dd style="margin-bottom:10px;">To be updated</dd>
	
	<dt id="answer5">Payment, Pricing & Promotions</dt>
	<dd style="margin-bottom:10px;">To be updated</dd>
	
	<dt id="answer6">Viewing Orders</dt>
	<dd style="margin-bottom:10px;">To be updated</dd>
	
	<dt id="answer7">Updating Account Information</dt>
	<dd style="margin-bottom:10px;">To be updated</dd>
</dl>
</div>