<?php
/**
 * 
 * Frontend Customer Service page.
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="policyArea">

<div class="pageHeader"> Site Policies </div>

<ul class="disc" style="margin-bottom:15px;">
	<li><a href="#shipping_delivery">Shipping & Delivery</a></li>
	<li><a href="#payment_return_refund">Payments, Returns and Refunds</a></li>
	<li><a href="#privacy_policy">Privacy of Information</a></li>
	<li><a href="#terms_conditions">Terms and Conditions of Use</a></li>
	<!--li><a href="#answer5">Payment, Pricing & Promotions</a></li>
	<li><a href="#answer6"></a></li>
	<li><a href="#answer7">Updating Account Information</a></li-->
</ul>
<p></p><dl>
	<dt id="shipping_delivery"><span class="hdr">Shipping & Delivery</span></dt>
	<dd style="margin-bottom:10px;">
	<ul><p></p>
		<ol><strong>1. Free Shipping</strong>
			<ul>Ekkitab provides free shipping to its customers for orders value of more than Rs.100 and for destinations within India. We will charge Rs. 30 for orders below Rs. 100. Cost of shipping to overseas locations will vary with location and will be mentioned in the Checkout pages when you make a purchase. Our free shipping policy may change from time to time and we reserve the right make such changes without notice.</ul><p></p></ol>
		
		<ol><strong>2. Delivery Period</strong>
			<ul>We mention estimated delivery time for each book on its description page.  We use reputed couriers for all our deliveries. For areas not served by reputed couriers, we will use Registered Parcel Services of Indian Postal Services. We are dependent on these agencies to honor the delivery period that we display again each book.</ul></ol>
	</ul>
	</dd>
	
	<dt id="payment_return_refund"><span class="hdr">Payments, Returns and Refunds</span></dt>
	<dd style="margin-bottom:10px;">
	<ul><p></p>
		<ol><strong>1. Mode of Payment</strong>
			<ul class="disc"> 
				We accept all major modes of payments. These are listed below:

				<li>All major credit cards issued by Indian or International banks</li>
				<li>Debit cards issued by Indian banks</li>
				<li>PayPal</li>
				<li>Pay by Cheque/Demand Draft</li>
				<li>Netbanking: Online transfer </li>
				<li>Paymate: Payment by mobile phone (This is currently unavailable but is in the process of being made available shortly)</li>
			</ul><p></p>
		</ol>

		<ol><strong>2. Payment by Cheque, MoneyOrder or Draft</strong>
			<ul> 
			All Cheques, MoneyOrders or Drafts should be drawn in favor of <strong>Ekkitab Educational Services India Pvt Ltd.</strong> and mailed to:<br/>
		    Ekkitab Educational Services Pvt. Ltd.,<br/>
		    #1134, 4th Floor, 100 ft. Road,<br/>
		    HAL II Stage,<br/>
		    Bangalore - 560008<p></p>
		</ol>

		<ol><strong>3. Return Policy</strong>
			<ul > 
		 
				You may return your purchase in original package within 7 days of receiving the shipment for a full refund after deducting shipping. 

				<p>This return policy is applicable for all nationally sourced editions. We do not accept returns of imported editions (stated explicitly as Imported Edition against the book). </p>
			</ul> <p></p>	
		</ol> 

		<ol><strong>4. Defective Goods</strong>
			<ul > 
				In case of receiving a defective or damaged shipment, please contact us and we will send you a replacement or refund your money.
			</ul> <p></p>	
		</ol>

		<ol><strong>5. Return Procedure</strong>
			<ul > 
				Your return should be packed in its original package and addressed to:<br/>

			   Ekkitab Educational Services Pvt. Ltd.,<br/>
			   #1134, 4th Floor, 100 ft. Road,<br/>
			   HAL II Stage,<br/>
			   Bangalore - 560008
			   <p>You should then email us at: <a href="mailto:returns@ekkitab.com">returns@ekkitab.com</a> mentioning order number, reason for return and dispatch date. We will acknowledge your email and ensure that as soon as your return is received, your credit is processed. </p>
			</ul> <p> </p>
		</ol>

	</ul>
	</dd>
	
	<dt id="privacy_policy"><span class="hdr">Privacy of Information</span></dt>
	<dd style="margin-bottom:10px;">
		<ul > 
	
			This website is operated by Ekkitab Educational Services India Pvt Ltd.

			<ol><strong>1. Confidential Customer Information</strong>

				<ul >At Ekkitab, we respect our customers and understand that you are concerned about privacy.		

					We collect personal information like your name, e-mail address, billing address, shipping address, phone number to identify or contact you. This information will not be used for any other purpose nor will it be given to any other third party except those that have a reason to require it, like courier or postal services in order to deliver your purchase. 

					We may be required by law to share personal information with courts or other government agencies if so ordered.

					We may use this information to contact you about new product offers if you so authorize such communication. 

					We do not collect or store any credit card details of our customers. All our transactions are routed through secured payment gateways that authorize the charges without sharing any credit card information with us.

					We definitely will not sell or rent your personal information to third parties for profit.

				</ul><p></p>
			</ol>
			<ol><strong>2. Security of Confidential Information</strong>

				<ul >Personal information collected by us is held in a relational database that is protected from unauthorized access both within and outside the company. As such the information is secure except in the instances when server security is breached by hostile attack. In such instances we shall immediately notify you of such a breach to enable you to take preventive action immediately.</ul><p></p>
			</ol> 

			<ol><strong>3. Cookies</strong> 

				<ul >We use cookies to enhance your shopping experience with us. We do not enable third-party access to our cookies nor do we have arrangements with other web sites to share customer visits with them.</ul><p></p>
			</ol>

			<ol><strong>4. Revisions in Privacy Policy</strong>

				<ul >Ekkitab reserves the right to modify this privacy policy at any time. This policy was last modified on 15th June 2010.</ul><p></p>
			</ol>

			<ol><strong>5. Questions?</strong>

				<ul >Please email all your questions about this privacy policy to <a href="mailto:support@ekkitab.com">support@ekkitab.com</a> or call us at +91 80-4173-2016. This telephone is manned from 10:00am through 5:00pm, Monday through Friday, except on holidays.</ul><p></p>
			</ol>
		</ul>
	</dd>
	
	<dt id="terms_conditions"><span class="hdr">Terms and Conditions of Use</span></dt>
	<dd style="margin-bottom:10px;">

		<ul>
			Welcome to Ekkitab.com, a website operated by Ekkitab Educational Services India Pvt Ltd. (Ekkitab) 

			<br/>By visiting  or shopping AT EKKITAB.COM, YOU ACCEPT THESE CONDITIONS. You should read these conditions carefully. 	

			<ol><strong>1. Applicable Law (Jurisdiction)</strong>
				<ul >
				The Ekkitab.com site is created and controlled by Ekkitab Educational Services India Pvt Ltd in the State of Karnataka, India. The laws of the Karnataka State will govern the Terms of Use, without giving effect to any principles of conflicts of laws.

				By visiting Ekkitab.com, you agree to submit to the nonexclusive personal jurisdiction of the courts located within Karnataka for any litigation.</ul><p></p>
			</ol>
			<ol><strong>2. Site Terms, Modification, and Severability</strong>
				<ul >Ekkitab reserves the right to make changes to our site, change the terms and conditions of use at any time without notice.</ul><p></p>
			</ol>
			<ol><strong>3. Disclaimer of Warranties and Limitation of Liability</strong>
				<ul > This site and all information made available to you through this site are provided by Ekkitab on an "AS IS" and "AS AVAILABLE" basis. Ekkitab makes no representations or warranties of any kind as to the operation of this site OR the content, information, products made available to you through this site. You agree that you are using this site at your own risk.</ul><p></p>
			</ol>
			<ol><strong>4. Trademarks</strong>
				<ul >Ekkitab owns the trademarks or service marks that are used on the Ekkitab.com site. All rights are reserved. These and other graphics, logos, service marks, trademarks may not be used without prior written consent of Ekkitab.</ul><p></p>
			</ol>
		</ul>
	</dd>
</dl>
</div>