<?php
/**
 * 
 * Frontend About Us page.
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>

<div class="mediaReleasesArea">
	<div class="pageHeader">In the News</div>
	<div class="clear"></div>
		<div class="newsArea">
			<p class="newsTitle"><a href="http://keralaitnews.com/news-outside-parks/other-cities/1395-ek-kitab-an-online-bookstore-with-a-donor-network" target="_blank"  >The Ekkitab Story - Online BookStore with a donor network.</a>
			<br>Web: Kerala IT News, dated 14th Sept. 2010</p>
			<div class="menuSep"></div>
			<div class="clear"><br/></div>
		</div>
		<div class="rightArea">
			<?php echo $this->getChildHtml('leftlink_menu'); ?>
		</div>
</div><!-- aboutUsArea -->