<?php
/**
 * 
 * Frontend News Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="linkHdr">In the News</div>
<div class="newsHline"><a href="#">Headline News Item 1 online bookstore I have ever seen.</a></div>
<div class="newsItem">Fast and free shipping, discounts and a large number of titles. I could not have expected more.</div> 
<div class="newsReadMore"><a href="#">Read more &raquo;</a></div>
<div class="newsHline"><a href="#">News Headline Item 2 online bookstore I have ever seen.</a></div>
<div class="newsItem">Fast and free shipping, discounts and a large number of titles. I could not have expected more.</div> 
<div class="newsReadMore"><a href="#">Read more &raquo;</a></div>
<div class="dottedLine"></div>
