<?php
/**
 * 
 * Frontend Static Block - Best sellers
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="promo-box" >
        <h3>Top books of the Month</h3>
	<table border="0" cellspacing="0">
		<tbody>
			<tr class="odd">
				<td><p class="product-image">
					<a href="<?php echo $this->getUrl("fiction/tales-from-shakespeare.html") ?>"  title="Tales from Shakespeare"> <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/best_selling_img04.jpg") ?>" border="0" width="95" /></a></p>
					<div class="clear product-description"><p><a href="<?php echo $this->getUrl("fiction/tales-from-shakespeare.html") ?>"  title="Tales from Shakespeare">Tales from Shakespeare</a></p><div>
				</td>
				<td><a href="<?php echo $this->getUrl("comics-graphic-novels.html") ?>">  <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/best_selling_img03.jpg") ?>" border="0" width="95" /></a>
				<div class="clear product-description">
				<p><a href="<?php echo $this->getUrl("comics-graphic-novels.html") ?>">John Coltrane</a></p>
				</div>
				</td>
				<td><a href="<?php echo $this->getUrl("comics-graphic-novels.html") ?>">  <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/furnitures_living_room.jpg") ?>" border="0" width="95" /></a>
				<div class="clear product-description">
				<p><a href="<?php echo $this->getUrl("comics-graphic-novels.html") ?>">Untitled Memoir</a></p>
				</div>
				</td>
				<td><a href="<?php echo $this->getUrl("comics-graphic-novels.html") ?>">  <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/best_selling_img06.jpg") ?>" border="0" width="95" /></a>
				<div class="clear product-description">
				<p><a href="<?php echo $this->getUrl("comics-graphic-novels.html") ?>">Across the Zodiac the Story of a Wrecked Record</a></p>
				</div>
				</td>
			</tr>
         	</tbody>
	</table>
</div>