<div class="promo-box" >
        <h3>Best Sellers</h3>
	<table border="0" cellspacing="0">
		<tbody>
			<tr class="odd">
				<td><p class="product-image">
					<a href="<?php echo $this->getUrl("fiction/tales-from-shakespeare.html") ?>"  title="Nostromo: A Tale of the Seaboard"> <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/best_selling_img01.jpg") ?>" border="0" width="95" /></a></p>
					<div class="clear product-description"><p><a href="<?php echo $this->getUrl("fiction/tales-from-shakespeare.html") ?>"  title="Nostromo: A Tale of the Seaboard">Nostromo: A Tale of the Seaboard</a></p><div>
				</td>
				<td><a href="<?php echo $this->getUrl("biography-autobiography.html") ?>">  <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/best_selling_img02.jpg") ?>" border="0" width="95" /></a>
				<div class="clear product-description">
				<p><a href="<?php echo $this->getUrl("biography-autobiography.html") ?>">Nostromo: A Tale of the Seaboard</a></p>
				</div>
				</td>
				<td><a href="<?php echo $this->getUrl("biography-autobiography.html") ?>">  <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/furnitures_living_room.jpg") ?>" border="0" width="95" /></a>
				<div class="clear product-description">
				<p><a href="<?php echo $this->getUrl("biography-autobiography.html") ?>">Roma: The Novel of Ancient Rome</a></p>
				</div>
				</td>
				<td><a href="<?php echo $this->getUrl("biography-autobiography.html") ?>">  <img class="product-img" src="<?php echo $this->getSkinUrl("images/media/best_selling_img04.jpg") ?>" border="0" width="95" /></a>
				<div class="clear product-description">
				<p><a href="<?php echo $this->getUrl("biography-autobiography.html") ?>">Ceremony in Death</a></p>
				</div>
				</td>
			</tr>
         	</tbody>
	</table>
</div>