<?php
/**
 * 
 * Frontend Testimonial Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php echo $this->getChildHtml('donate_book_blurb_home') ?>
<?php echo $this->getChildHtml('component2') ?>
<!--
<div class="linkHdr">Top Authors <span class="seeAllLink"> [<a href="" title="See All">See All</a>]</span> </div>
<ul>								
	<li><a href="<?php echo $this->getUrl('ekkitab_catalog/search/index/author/Amartya+Sen') ?>">Amartya Sen</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Arundhati+Roy') ?>">Arundhati Roy</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Amitav+Ghosh') ?>">Amitav Ghosh</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Subroto+Bagchi') ?>">Subroto Bagchi</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Gurcharan+Das') ?>">Gurcharan Das</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Pamuk+Orhan') ?>">Pamuk Orhan</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Kiran+Desai') ?>">Kiran Desai</a></li>
	<li><a href="<?php  echo $this->getUrl('ekkitab_catalog/search/index/author/Khushwant+Singh') ?>">Khushwant Singh</a></li>
</ul>
<div class="menuSep">&nbsp;</div>-->
<br class="clear" />


<!--div class="linkHdr">In the News</div>
<div class="newsHline"><a href="#">Headline News Item 1 online bookstore I have ever seen.</a></div>
<div class="newsItem">Fast and free shipping, discounts and a large number of titles. I could not have expected more.</div> 
<div class="newsReadMore"><a href="#">Read more &raquo;</a></div>
<div class="newsHline"><a href="#">News Headline Item 2 online bookstore I have ever seen.</a></div>
<div class="newsItem">Fast and free shipping, discounts and a large number of titles. I could not have expected more.</div> 
<div class="newsReadMore"><a href="#">Read more &raquo;</a></div>
<div class="dottedLine"></div-->

<!--div class="linkHdr">Donation Network</div>
<div class="testiText">One of the best Indian online bookstore I have ever seen. Fast and free shipping, discounts and a large number of titles. I could not have expected more.</div>
<div class="testiName">John Doe</div>
<div class="testiText">The prices are competitive and shipping is free. This, coupled with excellent customer support, makes ekkitab.com a site that I can heartily recommend to my friends and come back to myself whenever I am looking to buy books online.</div>
<div class="testiName">Anirbhan Ghosh</div>
<div class="dottedLine"></div-->
