<?php
/**
 * 
 * Frontend Testimonial Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="linkHdr">Celebrating 150 years of 
	<span class="largerFont">Rabindranath Tagore's</span>birth
</div><!-- linkHdr -->
<div class="tagoreArea">
	<div class="face">
		<img src="<?php echo $this->getSkinUrl('/images/tagore_face.jpg')?>" />
	</div><!-- face -->
	<img src="<?php echo $this->getSkinUrl('/images/tagore_poem.png')?>" />
	<div class="newsReadMore"><a href="<?php echo $this->getUrl('ekkitab_catalog/search/index/q/Rabindranath Tagore')?>">Special deals<br />on Tagore's books</a></div>
</div>