<?php
/**
 * 
 * Frontend Testimonial Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="tagoreHdr">Celebrating the 150<sup>th</sup> year of 
	<span class="largerFont">Rabindranath Tagore's</span> birth anniversary
</div><!-- linkHdr -->
<div class="tagoreArea">
	<div class="face">
		<img src="<?php echo $this->getSkinUrl('/images/tagore_face.jpg')?>" />
	</div><!-- face -->
	Where the mind is without fear
	and the head is held high,<br />
	Where knowledge is free;<br />
	Where the world has not been broken 
	up into fragments by narrow domestic
	walls;<br />
	 Where words come out from the
	depth of truth;<br />
	Where tireless striving<br />
	stretches its arms towards<br />
	perfection;<br />
	Where the clear stream of reason
	has not lost its way<br /> into the
	dreary desert sand of dead habit;<br />
	Where the mind is led forward 
	by thee into ever-widening 
	thought and action-<br />
	into that heaven of freedom,
	my Father,<br />
	Let my country awake.<br />
	<div class="newsReadMore"><a href="<?php echo $this->getUrl('ekkitab_catalog/search/index/q/Rabindranath Tagore')?>">Books on Tagore</a></div>
</div>