<?php
/**
 * 
 * Frontend Testimonial Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Jan 5, 2010
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<div class="linkHdr">Testimonials</div>
<div class="testiText">One of the best Indian online bookstore I have ever seen. Fast and free shipping, discounts and a large number of titles. I could not have expected more.</div><!-- testiText -->
<div class="testiName">John Doe</div>
<div class="testiText">The prices are competitive and shipping is free. This, coupled with excellent customer support, makes ekkitab.com a site that I can heartily recommend to my friends and come back to myself whenever I am looking to buy books online.</div><!-- testiText -->
<div class="testiName">Anirbhan Ghosh</div>
<div class="dottedLine"></div>
