<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
		$authors= $this->getTopAuthors();
		$_count = is_array($authors)?count($authors):$authors->count(); 
		$randNo =11;
?>
 <script language="JavaScript"  type="text/javascript">
    function searchAuthor(query){
		var searchForm = document.forms.search_author;
		searchForm.<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>.value=query;
		searchForm.submit();
	}
</script>
<div class="popular-authors left" >
	<div class="head" >
			<h4>Top Authors </h4>
	</div>	
	<div class="content">
		<ul>
		<?php if($_count): ?>
		<form name="search_author" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
			<input type="hidden" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="" />
		</form>
			<?php foreach ($authors as $author): ?>
				<?php if($author->getIsActive()): 
						$randNo = 10 * rand(9, 15);
					?>
					<li>
						<a style="font-size:<?php echo $randNo?>%;" href="javascript:searchAuthor('<?php echo $author->getAuthor()?>');"><?php echo $this->htmlEscape($author->getAuthor()) ?></a>&nbsp;
					</li>
				<?php endif; ?>
			<?php endforeach ?>
		<?php else: ?>
			This section will be updated soon
		<?php endif; ?>
		</ul>
	</div>	
</div>