<?php
/**
 * 
 * Frontend Popular Authors Template
 * @category   design/ekkitab
 * @author Anisha (anisha@ekkitab.com)
 * @version 1.0 Nov 17, 2009
 * 
 * @copyright  COPYRIGHT (C) 2009 Ekkitab Educational Services India Pvt. Ltd.
 * @license    All Rights Reserved. All material contained in this file (including, but not limited to, text, images, graphics, HTML, programming code and scripts) 
 * constitute proprietary and  * confidential information protected by copyright laws, trade secret and other laws. No part of this software may be copied, reproduced, modified or 
 * distributed in any form or by any means, or stored in a database or retrieval system without the prior written permission of Ekkitab Educational Services.
 * 
 * 
 */
?>
<?php 
	$authors= $this->getTopAuthors();
	$_count = is_array($authors)?count($authors):$authors->count(); 
?>
 <script language="JavaScript"  type="text/javascript">
    function searchAuthor(query){
		var searchForm = document.forms.search_author;
		searchForm.<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>.value=query;
		searchForm.<?php echo $this->helper('ekkitab_catalog')->getQueryFilterName() ?>.value="author";
		searchForm.submit();
	}
</script>
<div class="linkHdr">Popular Authors</div><!-- linkHdr -->
<?php if($_count): ?>
	<ul>
		<?php foreach ($authors as $author): ?>
			<?php if($author->getIsActive()): 
					$randNo = 10 * $author->getPopularity();
					$url = $this->helper('ekkitab_catalog')->getSearchResultByIndexUrl(null,array($this->helper('ekkitab_catalog')->getQueryParamName()=>urlencode($author->getAuthor()),$this->helper('ekkitab_catalog')->getQueryFilterName() => 'author'));
				?>
				<li>
					<a href="<?php echo $url ?>"><?php echo $this->htmlEscape($author->getAuthor()) ?></a></li>
			<?php endif; ?>
		<?php endforeach ?>
	</ul>
	<div class="seeAll"><a href="<?php echo $this->getUrl('ekkitab_catalog/author/viewAll') ?>">See all &raquo;</a></div><!-- seeAll -->
<?php else: ?>
	<li>This section will be updated soon</li>
<?php endif; ?>
