#!/bin/bash
export JAVA_HOME=/usr/lib/jvm/java-6-sun
export EC2_HOME=$EKKITAB_HOME/ec2-api-tools-1.3-53907
export PATH=$EC2_HOME/bin:$PATH
export EC2_PRIVATE_KEY_DIR=/$EKKITAB_HOME/amazonservers/prod/aws
export EC2_CERT="$EC2_PRIVATE_KEY_DIR/cert-HWUNGVB47ADH66JTHSBNVTO3U3JJL4H3.pem"
export EC2_PRIVATE_KEY="$EC2_PRIVATE_KEY_DIR/pk-HWUNGVB47ADH66JTHSBNVTO3U3JJL4H3.pem"
export AWS_ACCESS_KEY="AKIAJJ52V7D5SWIIFXKQ"
export AWS_SECRET_ACCESS_KEY="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"
