<?php

$_product =  Mage::getModel('ekkitab_catalog/product')
			->setStoreId(Mage::app()->getStore()->getId())
			->load("000641414800X","isbn");
?>

<div class="contentArea padderLeft10px">
	<img src="<?php echo $this->getSkinUrl('/images/overleaf_beam_offer_121110.jpg')?>" usemap ="#beamMap" border="0"/>
</div>


<?php if($_product && $_product->getId() > 0 ){
?>
	<form action="<?php echo $this->helper('ekkitab_catalog')->getCartUrl($_product->getId(),$this->helper('core/url')->getCurrentUrl()) ?>" method="post" id="product_addtocart_form">
		<fieldset class="no-display">
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
		</fieldset>
	</form>
	<map name="beamMap">
	  <area shape="rect" coords="577,585,665,615" href="#" onClick="productAddToCartForm.submit(); return false;" alt="Buy Now" />
	</map>
<?php }
?>

<script type="text/javascript">
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function() {
        if(this.validator.validate()) {
            this.form.submit();
        }
    }.bind(productAddToCartForm);

</script>

