<?php
/**
 * Magento
 *
 */
?>
<!-- // this is testing -->
<div class="topSearchArea">
	<form id="custom_search_mini_form" action="<?php echo $this->helper('ekkitab_catalog')->getFormSearchResultByIndexUrl() ?>" method="get">
		<fieldset>
			<div class="searchBar">
			<div class="searchText"><?php echo $this->__('Search for') ?></div>

			<input id="search" type="text" class="textField" name="<?php echo $this->helper('ekkitab_catalog')->getQueryParamName() ?>" value="<?php echo urldecode($this->helper('ekkitab_catalog')->getEscapedQueryText()) ?>" />
			
			<input type="hidden" name="<?php echo $this->helper('ekkitab_catalog')->getQueryFilterName() ?>" value="" />

			<div class="searchBut"><input type="image" src="<?php echo $this->getSkinUrl('images/search_button.png') ?>"  width="21" height="21" alt="<?php echo $this->__('Go') ?>" border="0" /></div>


			<div id="search_autocomplete" class="search-autocomplete"></div>

			<script type="text/javascript">
			//<![CDATA[
				var searchForm = new Varien.searchForm('custom_search_mini_form', 'search', '');
				searchForm.initAutocomplete('<?php echo $this->helper('ekkitab_catalog')->getSuggestUrl() ?>', 'search_autocomplete');
			//]]>
			</script>

			<?php echo $this->getChildHtml('topUserLinks')?> 
           </div> 
			<div class="filterSearch">
			<div class="searchText"><?php echo $this->__('In') ?></div> <select name="<?php echo $this->helper('ekkitab_catalog')->getQueryFilterName() ?>" >
			<option id="searchBy" value="" > All </option>
			<option id="searchBy" value="author" <?php if($this->helper('ekkitab_catalog')->getQueryFilterByText()=='author'): ?> selected="selected"<?php endif ?>> Author </option>
            <option id="searchBy"value="title" <?php if($this->helper('ekkitab_catalog')->getQueryFilterByText()=='title'): ?> selected="selected"<?php endif ?>> Title </option>
            <option id="searchBy"value="isbn" <?php if($this->helper('ekkitab_catalog')->getQueryFilterByText()=='isbn'): ?> selected="selected"<?php endif ?>> ISBN </option>
			</select></div>

		</fieldset>
	</form>
	<div class="clear"></div>
</div>
