<?php
/**
 * Magento
 *
 */
?>
<!-- // this is testing -->
<div class="topSearchArea">
	<form id="custom_search_mini_form" action="<?php echo $this->helper('ekkitab_catalog')->getFormSearchResultByIndexUrl() ?>" method="get">
		<fieldset>
			<div class="searchText"><?php echo $this->__('Search for') ?></div>

			<input id="search" type="text" class="textField" name="<?php echo $this->helper('ekkitab_catalog')->getQueryParamName() ?>" value="<?php echo $this->helper('ekkitab_catalog')->getEscapedQueryText() ?>" />
			
			<input type="hidden" name="<?php echo $this->helper('ekkitab_catalog')->getQueryFilterName() ?>" value="" />

			<div class="searchBut"><input type="image" src="<?php echo $this->getSkinUrl('images/search_button.png') ?>"  width="21" height="21" alt="<?php echo $this->__('Go') ?>" border="0" /></div>


			<div id="search_autocomplete" class="search-autocomplete"></div>

			<script type="text/javascript">
			//<![CDATA[
				var searchForm = new Varien.searchForm('custom_search_mini_form', 'search', '');
				searchForm.initAutocomplete('<?php echo $this->helper('ekkitab_catalog')->getSuggestUrl() ?>', 'search_autocomplete');
			//]]>
			</script>

			<?php echo $this->getChildHtml('topUserLinks')?> 
		</fieldset>
	</form>
	<div class="clear"></div>
</div>
